### ISSUE TITLE
NullPointerException when sending data to an already closed connection

### ISSUE THREAD

**Issue by dougbradbury** [eventmachine/eventmachine#122]
I encountered this exception when trying to send data to an already closed connection

```
NativeException java.lang.NullPointerException: null
com/rubyeventmachine/EmReactor.java:434:in `sendData'
com/rubyeventmachine/EmReactor.java:438:in `sendData'
```

full stack trace here:  https://gist.github.com/662499

```
Dkbrpc Server Error Native
Exception java.lang.NullPointerException: null
com/rubyeventmachine/EmReactor.java:434:in `sendData'
com/rubyeventmachine/EmReactor.java:438:in `sendData'
lib/gems/gems/eventmachine-0.12.11-java/lib/em/connection.rb:227:in `send_data'
lib/gems/gems/dkbrpc-0.1.11/lib/dkbrpc/fast_message_protocol.rb:25:in `send_message'
lib/gems/gems/dkbrpc-0.1.11/lib/dkbrpc/outgoing_connection.rb:23:in `remote_call'
lib/gems/gems/dkbrpc-0.1.11/lib/dkbrpc/server.rb:20:in `method_missing'
lib/gems/gems/eventmachine-0.12.11-java/lib/eventmachine.rb:257:in `call'
lib/gems/gems/eventmachine-0.12.11-java/lib/eventmachine.rb:257:in `schedule'
lib/gems/gems/eventmachine-0.12.11-java/lib/eventmachine.rb:940:in `call'
lib/gems/gems/eventmachine-0.12.11-java/lib/eventmachine.rb:940:in `run_deferred_callbacks'
lib/gems/gems/eventmachine-0.12.11-java/lib/eventmachine.rb:937:in `each'
lib/gems/gems/eventmachine-0.12.11-java/lib/eventmachine.rb:937:in `run_deferred_callbacks'
lib/gems/gems/eventmachine-0.12.11-java/lib/eventmachine.rb:1399:in `event_callback'
lib/gems/gems/eventmachine-0.12.11-java/lib/jeventmachine.rb:83:in `eventCallback'
lib/gems/gems/eventmachine-0.12.11-java/lib/jeventmachine.rb:102:in `run_machine'
lib/gems/gems/eventmachine-0.12.11-java/lib/eventmachine.rb:195:in `run'
pcres/server/main.rb:69:in `start_eventmachine'
pcres/server/main.rb:68:in `initialize'
pcres/server/main.rb:68:in `new'
pcres/server/main.rb:68:in `start_eventmachine'
pcres/server/main.rb:27:in `run'
<script>:1
```

**Comment by blewa** [comment]
Is this thing on?

**Comment by sodabrew** [comment]
This thing is on. I don't have a reproduction case here and haven't yet put much time into the Java implementation since I started as a maintainer here. Further debugging information welcomed!

**Comment by blewa** [comment]
Was @dougbradbury's example not enough?  I can very easily reproduce by creating websocket connection and attempting to send to it after the client has disconnected (in this case when the browser tab closes).

**Comment by blewa** [comment]
Oh sorry, I thought he had a better example in hist gist.  I'll see if I can put together a simple example.

**Comment by blewa** [comment]
Alright, here's a quick example I put together to show the crash.  To simulate, run the ruby script, bring up the HTML in your browser and wait one or two ticks.  Then close your browser and enjoy the stacktrace fireworks on your console :)

https://gist.github.com/blewa/0859a1d5fcc31e6ab7e0

**Comment by sodabrew** [comment]
Thank you! I will give it a try this week!

Are you using JRuby 1.7.x or JRuby-9000 for this test?

**Comment by blewa** [comment]
I updated the gist to show output from both versions as they both crash.
