### ISSUE TITLE
https:///host.com/ causes Seg Fault on solaris  (three forward slashes instead of two)

### ISSUE THREAD

**Issue by wkonkel** [eventmachine/eventmachine#376]
Due to a bug in our code, three slashes were appearing in a URL instead of the normal two.  What was unexpected was a segfault.

EM.run do
  multi = EM::MultiRequest.new
  url = 'https:///ajax.googleapis.com/ajax/libs/jquery/1.8.0/jquery.min.js'
  multi.add(url, EM::HttpRequest.new(url).get)
  multi.callback {EM.stop}
end

Ruby:  ruby 1.9.2p290 (2011-07-09 revision 32553) [x86_64-solaris2.11]

Full trace:  https://gist.github.com/5f011dc347fd95e24ef2

**Comment by sodabrew** [comment]
EM::MultiRequest is now maintained at https://github.com/igrigorik/em-http-request

I have copied this ticket to igrigorik/em-http-request#280

**Comment by sodabrew** [comment]
Minimal repro case without EM::MultiRequest. This fails gracefully on OS X and Linux, but crashes on Solaris:

``` ruby
require 'eventmachine'
EM.run { EM.connect_server '/foo', 123 }
```
```
EventMachine::ConnectionError: unable to resolve server address
```

On Solaris:
```
(irb):2: [BUG] Segmentation fault
ruby 1.9.3p484 (2013-11-22 revision 43786) [amd64-solaris2.11]

-- Control frame information -----------------------------------------------
c:0029 p:---- s:0103 b:0103 l:000102 d:000102 CFUNC  :connect_server
c:0028 p:0019 s:0098 b:0098 l:000288 d:000097 BLOCK  (irb):2
c:0027 p:---- s:0096 b:0096 l:000095 d:000095 FINISH
c:0026 p:---- s:0094 b:0094 l:000093 d:000093 CFUNC  :call
c:0025 p:---- s:0092 b:0092 l:000091 d:000091 CFUNC  :run_machine
c:0024 p:0321 s:0089 b:0089 l:000088 d:000088 METHOD /export/home/aaron/eventmachine/lib/eventmachine.rb:187
c:0023 p:0015 s:0082 b:0082 l:000288 d:001138 EVAL   (irb):2
c:0022 p:---- s:0080 b:0080 l:000079 d:000079 FINISH
c:0021 p:---- s:0078 b:0078 l:000077 d:000077 CFUNC  :eval
c:0020 p:0028 s:0071 b:0071 l:000070 d:000070 METHOD /usr/ruby/1.9/lib/ruby/1.9.1/irb/workspace.rb:80
c:0019 p:0033 s:0064 b:0063 l:000062 d:000062 METHOD /usr/ruby/1.9/lib/ruby/1.9.1/irb/context.rb:254
c:0018 p:0031 s:0058 b:0058 l:0025a8 d:000057 BLOCK  /usr/ruby/1.9/lib/ruby/1.9.1/irb.rb:159
c:0017 p:0042 s:0050 b:0050 l:000049 d:000049 METHOD /usr/ruby/1.9/lib/ruby/1.9.1/irb.rb:273
c:0016 p:0011 s:0045 b:0045 l:0025a8 d:000044 BLOCK  /usr/ruby/1.9/lib/ruby/1.9.1/irb.rb:156
c:0015 p:0144 s:0041 b:0041 l:000024 d:000040 BLOCK  /usr/ruby/1.9/lib/ruby/1.9.1/irb/ruby-lex.rb:243
c:0014 p:---- s:0038 b:0038 l:000037 d:000037 FINISH
c:0013 p:---- s:0036 b:0036 l:000035 d:000035 CFUNC  :loop
c:0012 p:0009 s:0033 b:0033 l:000024 d:000032 BLOCK  /usr/ruby/1.9/lib/ruby/1.9.1/irb/ruby-lex.rb:229
c:0011 p:---- s:0031 b:0031 l:000030 d:000030 FINISH
c:0010 p:---- s:0029 b:0029 l:000028 d:000028 CFUNC  :catch
c:0009 p:0023 s:0025 b:0025 l:000024 d:000024 METHOD /usr/ruby/1.9/lib/ruby/1.9.1/irb/ruby-lex.rb:228
c:0008 p:0046 s:0022 b:0022 l:0025a8 d:0025a8 METHOD /usr/ruby/1.9/lib/ruby/1.9.1/irb.rb:155
c:0007 p:0011 s:0019 b:0019 l:000508 d:000018 BLOCK  /usr/ruby/1.9/lib/ruby/1.9.1/irb.rb:70
c:0006 p:---- s:0017 b:0017 l:000016 d:000016 FINISH
c:0005 p:---- s:0015 b:0015 l:000014 d:000014 CFUNC  :catch
c:0004 p:0183 s:0011 b:0011 l:000508 d:000508 METHOD /usr/ruby/1.9/lib/ruby/1.9.1/irb.rb:69
c:0003 p:0039 s:0006 b:0006 l:0022c8 d:002518 EVAL   /usr/bin/irb:12
c:0002 p:---- s:0004 b:0004 l:000003 d:000003 FINISH
c:0001 p:0000 s:0002 b:0002 l:0022c8 d:0022c8 TOP   

-- Ruby level backtrace information ----------------------------------------
/usr/bin/irb:12:in `<main>'
/usr/ruby/1.9/lib/ruby/1.9.1/irb.rb:69:in `start'
/usr/ruby/1.9/lib/ruby/1.9.1/irb.rb:69:in `catch'
/usr/ruby/1.9/lib/ruby/1.9.1/irb.rb:70:in `block in start'
/usr/ruby/1.9/lib/ruby/1.9.1/irb.rb:155:in `eval_input'
/usr/ruby/1.9/lib/ruby/1.9.1/irb/ruby-lex.rb:228:in `each_top_level_statement'
/usr/ruby/1.9/lib/ruby/1.9.1/irb/ruby-lex.rb:228:in `catch'
/usr/ruby/1.9/lib/ruby/1.9.1/irb/ruby-lex.rb:229:in `block in each_top_level_statement'
/usr/ruby/1.9/lib/ruby/1.9.1/irb/ruby-lex.rb:229:in `loop'
/usr/ruby/1.9/lib/ruby/1.9.1/irb/ruby-lex.rb:243:in `block (2 levels) in each_top_level_statement'
/usr/ruby/1.9/lib/ruby/1.9.1/irb.rb:156:in `block in eval_input'
/usr/ruby/1.9/lib/ruby/1.9.1/irb.rb:273:in `signal_status'
/usr/ruby/1.9/lib/ruby/1.9.1/irb.rb:159:in `block (2 levels) in eval_input'
/usr/ruby/1.9/lib/ruby/1.9.1/irb/context.rb:254:in `evaluate'
/usr/ruby/1.9/lib/ruby/1.9.1/irb/workspace.rb:80:in `evaluate'
/usr/ruby/1.9/lib/ruby/1.9.1/irb/workspace.rb:80:in `eval'
(irb):2:in `irb_binding'
/export/home/aaron/eventmachine/lib/eventmachine.rb:187:in `run'
/export/home/aaron/eventmachine/lib/eventmachine.rb:187:in `run_machine'
/export/home/aaron/eventmachine/lib/eventmachine.rb:187:in `call'
(irb):2:in `block in irb_binding'
(irb):2:in `connect_server'

-- C level backtrace information -------------------------------------------
/usr/ruby/1.9/lib/amd64/libruby.so.1'rb_vm_bugreport+0x55 [0xffff80ffbcc03831]
/usr/ruby/1.9/lib/amd64/libruby.so.1'report_bug+0xf2 [0xffff80ffbcabbf0e]
/usr/ruby/1.9/lib/amd64/libruby.so.1'rb_bug+0xbb [0xffff80ffbcabbfe3]
/usr/ruby/1.9/lib/amd64/libruby.so.1'0x1772bb [0xffff80ffbcb772bb]
/lib/amd64/libc.so.1'__sighndlr+0x6 [0xffff80ffbf515536]
/lib/amd64/libc.so.1'call_user_handler+0x2ce [0xffff80ffbf5089b6]
[0x35b65]
/lib/amd64/libc.so.1'_SUNW_Unwind_RaiseException+0x55 [0xffff80ffbf51d1c5]
/usr/lib/amd64/libstdc++.so.6.0.18'__cxa_throw+0x59 [0xffff80ffbdafbfc9]
/export/home/aaron/eventmachine/lib/rubyeventmachine.so'_ZN14EventMachine_t15ConnectToServerEPKciS1_i+0x497 [0xffff80ffbc31f1e7]
/export/home/aaron/eventmachine/lib/rubyeventmachine.so'_ZL16t_connect_servermmm+0x35 [0xffff80ffbc31b995]
/usr/ruby/1.9/lib/amd64/libruby.so.1'vm_exec_core+0x38f1 [0xffff80ffbcbd0ac9]
/usr/ruby/1.9/lib/amd64/libruby.so.1'vm_exec+0x67a [0xffff80ffbcc015b2]
/usr/ruby/1.9/lib/amd64/libruby.so.1'rb_vm_invoke_proc+0xc9b [0xffff80ffbcbffecb]
/usr/ruby/1.9/lib/amd64/libruby.so.1'proc_call+0x6a [0xffff80ffbcac3fee]
/usr/ruby/1.9/lib/amd64/libruby.so.1'vm_call0+0x74e [0xffff80ffbcbf0b16]
/usr/ruby/1.9/lib/amd64/libruby.so.1'rb_funcall+0x463 [0xffff80ffbcbf2bdf]
/export/home/aaron/eventmachine/lib/rubyeventmachine.so'_ZL22event_callback_wrappermiPKcm+0x188 [0xffff80ffbc31ad98]
/export/home/aaron/eventmachine/lib/rubyeventmachine.so'_ZN14EventMachine_t10_RunTimersEv+0x67 [0xffff80ffbc31ddb7]
/export/home/aaron/eventmachine/lib/rubyeventmachine.so'_ZN14EventMachine_t3RunEv+0x20 [0xffff80ffbc31ec20]
/export/home/aaron/eventmachine/lib/rubyeventmachine.so'_ZL29t_run_machine_without_threadsm+0x9 [0xffff80ffbc31a2a9]
/usr/ruby/1.9/lib/amd64/libruby.so.1'vm_exec_core+0x38c9 [0xffff80ffbcbd0aa1]
/usr/ruby/1.9/lib/amd64/libruby.so.1'vm_exec+0x67a [0xffff80ffbcc015b2]
/usr/ruby/1.9/lib/amd64/libruby.so.1'eval_string_with_cref+0x2f7 [0xffff80ffbcbfa82f]
/usr/ruby/1.9/lib/amd64/libruby.so.1'eval_string+0x15 [0xffff80ffbcbfac45]
/usr/ruby/1.9/lib/amd64/libruby.so.1'rb_f_eval+0x116 [0xffff80ffbcbfad5e]
/usr/ruby/1.9/lib/amd64/libruby.so.1'vm_exec_core+0x38be [0xffff80ffbcbd0a96]
/usr/ruby/1.9/lib/amd64/libruby.so.1'vm_exec+0x67a [0xffff80ffbcc015b2]
/usr/ruby/1.9/lib/amd64/libruby.so.1'loop_i+0x8c2 [0xffff80ffbcbf980e]
/usr/ruby/1.9/lib/amd64/libruby.so.1'rb_rescue2+0x2ab [0xffff80ffbcac115b]
/usr/ruby/1.9/lib/amd64/libruby.so.1'rb_f_loop+0x3a [0xffff80ffbcbf99f2]
/usr/ruby/1.9/lib/amd64/libruby.so.1'vm_exec_core+0x38c9 [0xffff80ffbcbd0aa1]
/usr/ruby/1.9/lib/amd64/libruby.so.1'vm_exec+0x67a [0xffff80ffbcc015b2]
/usr/ruby/1.9/lib/amd64/libruby.so.1'catch_i+0x967 [0xffff80ffbcbfd853]
/usr/ruby/1.9/lib/amd64/libruby.so.1'rb_catch_obj+0x10f [0xffff80ffbcbfdbfb]
/usr/ruby/1.9/lib/amd64/libruby.so.1'rb_f_catch+0x47 [0xffff80ffbcbfda87]
/usr/ruby/1.9/lib/amd64/libruby.so.1'vm_exec_core+0x38be [0xffff80ffbcbd0a96]
/usr/ruby/1.9/lib/amd64/libruby.so.1'vm_exec+0x67a [0xffff80ffbcc015b2]
/usr/ruby/1.9/lib/amd64/libruby.so.1'catch_i+0x967 [0xffff80ffbcbfd853]
/usr/ruby/1.9/lib/amd64/libruby.so.1'rb_catch_obj+0x10f [0xffff80ffbcbfdbfb]
/usr/ruby/1.9/lib/amd64/libruby.so.1'rb_f_catch+0x47 [0xffff80ffbcbfda87]
/usr/ruby/1.9/lib/amd64/libruby.so.1'vm_exec_core+0x38be [0xffff80ffbcbd0a96]
/usr/ruby/1.9/lib/amd64/libruby.so.1'vm_exec+0x67a [0xffff80ffbcc015b2]
/usr/ruby/1.9/lib/amd64/libruby.so.1'rb_iseq_eval_main+0x2b [0xffff80ffbcc016e3]
/usr/ruby/1.9/lib/amd64/libruby.so.1'ruby_exec_internal+0x87 [0xffff80ffbcac03ef]
/usr/ruby/1.9/lib/amd64/libruby.so.1'ruby_exec_node+0x1e [0xffff80ffbcac04ce]
/usr/ruby/1.9/lib/amd64/libruby.so.1'ruby_run_node+0x24 [0xffff80ffbcac0494]
/usr/ruby/1.9/bin/ruby'main+0x4c [0x400ec8]
/usr/ruby/1.9/bin/ruby'0xd1c [0x400d1c]

-- Other runtime information -----------------------------------------------

* Loaded script: irb

* Loaded features:

    0 enumerator.so
    1 /usr/ruby/1.9/lib/ruby/1.9.1/amd64-solaris2.11/enc/encdb.so
    2 /usr/ruby/1.9/lib/ruby/1.9.1/amd64-solaris2.11/enc/trans/transdb.so
    3 /usr/ruby/1.9/lib/ruby/1.9.1/rubygems/defaults.rb
    4 /usr/ruby/1.9/lib/ruby/1.9.1/amd64-solaris2.11/rbconfig.rb
    5 /usr/ruby/1.9/lib/ruby/1.9.1/rubygems/deprecate.rb
    6 /usr/ruby/1.9/lib/ruby/1.9.1/rubygems/exceptions.rb
    7 /usr/ruby/1.9/lib/ruby/1.9.1/rubygems/custom_require.rb
    8 /usr/ruby/1.9/lib/ruby/1.9.1/rubygems.rb
    9 /usr/ruby/1.9/lib/ruby/1.9.1/thread.rb
   10 /usr/ruby/1.9/lib/ruby/1.9.1/monitor.rb
   11 /usr/ruby/1.9/lib/ruby/1.9.1/amd64-solaris2.11/pathname.so
   12 /usr/ruby/1.9/lib/ruby/1.9.1/pathname.rb
   13 /usr/ruby/1.9/lib/ruby/gems/1.9.1/gems/bundler-1.7.12/lib/bundler/constants.rb
   14 /usr/ruby/1.9/lib/ruby/1.9.1/amd64-solaris2.11/etc.so
   15 /usr/ruby/1.9/lib/ruby/1.9.1/rubygems/config_file.rb
   16 /usr/ruby/1.9/lib/ruby/1.9.1/rubygems/version.rb
   17 /usr/ruby/1.9/lib/ruby/1.9.1/rubygems/requirement.rb
   18 /usr/ruby/1.9/lib/ruby/gems/1.9.1/gems/bundler-1.7.12/lib/bundler/rubygems_integration.rb
   19 /usr/ruby/1.9/lib/ruby/gems/1.9.1/gems/bundler-1.7.12/lib/bundler/current_ruby.rb
   20 /usr/ruby/1.9/lib/ruby/1.9.1/rubygems/dependency.rb
   21 /usr/ruby/1.9/lib/ruby/gems/1.9.1/gems/bundler-1.7.12/lib/bundler/shared_helpers.rb
   22 /usr/ruby/1.9/lib/ruby/1.9.1/fileutils.rb
   23 /usr/ruby/1.9/lib/ruby/gems/1.9.1/gems/bundler-1.7.12/lib/bundler/gem_path_manipulation.rb
   24 /usr/ruby/1.9/lib/ruby/1.9.1/rubygems/platform.rb
   25 /usr/ruby/1.9/lib/ruby/1.9.1/rubygems/specification.rb
   26 /usr/ruby/1.9/lib/ruby/gems/1.9.1/gems/bundler-1.7.12/lib/bundler/gem_helpers.rb
   27 /usr/ruby/1.9/lib/ruby/gems/1.9.1/gems/bundler-1.7.12/lib/bundler/match_platform.rb
   28 /usr/ruby/1.9/lib/ruby/gems/1.9.1/gems/bundler-1.7.12/lib/bundler/rubygems_ext.rb
   29 /usr/ruby/1.9/lib/ruby/gems/1.9.1/gems/bundler-1.7.12/lib/bundler/version.rb
   30 /usr/ruby/1.9/lib/ruby/gems/1.9.1/gems/bundler-1.7.12/lib/bundler.rb
   31 /usr/ruby/1.9/lib/ruby/gems/1.9.1/gems/bundler-1.7.12/lib/bundler/settings.rb
   32 /usr/ruby/1.9/lib/ruby/1.9.1/amd64-solaris2.11/digest.so
   33 /usr/ruby/1.9/lib/ruby/1.9.1/digest.rb
   34 /usr/ruby/1.9/lib/ruby/1.9.1/amd64-solaris2.11/digest/sha1.so
   35 /usr/ruby/1.9/lib/ruby/1.9.1/set.rb
   36 /usr/ruby/1.9/lib/ruby/gems/1.9.1/gems/bundler-1.7.12/lib/bundler/definition.rb
   37 /usr/ruby/1.9/lib/ruby/gems/1.9.1/gems/bundler-1.7.12/lib/bundler/dependency.rb
   38 /usr/ruby/1.9/lib/ruby/gems/1.9.1/gems/bundler-1.7.12/lib/bundler/ruby_dsl.rb
   39 /usr/ruby/1.9/lib/ruby/gems/1.9.1/gems/bundler-1.7.12/lib/bundler/dsl.rb
   40 /usr/ruby/1.9/lib/ruby/gems/1.9.1/gems/bundler-1.7.12/lib/bundler/source_list.rb
   41 /usr/ruby/1.9/lib/ruby/gems/1.9.1/gems/bundler-1.7.12/lib/bundler/source.rb
   42 /usr/ruby/1.9/lib/ruby/1.9.1/uri/common.rb
   43 /usr/ruby/1.9/lib/ruby/1.9.1/uri/generic.rb
   44 /usr/ruby/1.9/lib/ruby/1.9.1/uri/ftp.rb
   45 /usr/ruby/1.9/lib/ruby/1.9.1/uri/http.rb
   46 /usr/ruby/1.9/lib/ruby/1.9.1/uri/https.rb
   47 /usr/ruby/1.9/lib/ruby/1.9.1/uri/ldap.rb
   48 /usr/ruby/1.9/lib/ruby/1.9.1/uri/ldaps.rb
   49 /usr/ruby/1.9/lib/ruby/1.9.1/uri/mailto.rb
   50 /usr/ruby/1.9/lib/ruby/1.9.1/uri.rb
   51 /usr/ruby/1.9/lib/ruby/1.9.1/rubygems/user_interaction.rb
   52 /usr/ruby/1.9/lib/ruby/1.9.1/rubygems/remote_fetcher.rb
   53 /usr/ruby/1.9/lib/ruby/1.9.1/rubygems/errors.rb
   54 /usr/ruby/1.9/lib/ruby/1.9.1/rubygems/text.rb
   55 /usr/ruby/1.9/lib/ruby/1.9.1/rubygems/spec_fetcher.rb
   56 /usr/ruby/1.9/lib/ruby/gems/1.9.1/gems/bundler-1.7.12/lib/bundler/source/rubygems.rb
   57 /usr/ruby/1.9/lib/ruby/1.9.1/rubygems/path_support.rb
   58 /export/home/aaron/eventmachine/lib/em/version.rb
   59 /usr/ruby/1.9/lib/ruby/gems/1.9.1/gems/bundler-1.7.12/lib/bundler/source/path.rb
   60 /usr/ruby/1.9/lib/ruby/1.9.1/amd64-solaris2.11/strscan.so
   61 /usr/ruby/1.9/lib/ruby/gems/1.9.1/gems/bundler-1.7.12/lib/bundler/source/git.rb
   62 /usr/ruby/1.9/lib/ruby/gems/1.9.1/gems/bundler-1.7.12/lib/bundler/lockfile_parser.rb
   63 /usr/ruby/1.9/lib/ruby/gems/1.9.1/gems/bundler-1.7.12/lib/bundler/lazy_specification.rb
   64 /usr/ruby/1.9/lib/ruby/1.9.1/tsort.rb
   65 /usr/ruby/1.9/lib/ruby/1.9.1/forwardable.rb
   66 /usr/ruby/1.9/lib/ruby/gems/1.9.1/gems/bundler-1.7.12/lib/bundler/spec_set.rb
   67 /usr/ruby/1.9/lib/ruby/gems/1.9.1/gems/bundler-1.7.12/lib/bundler/environment.rb
   68 /usr/ruby/1.9/lib/ruby/gems/1.9.1/gems/bundler-1.7.12/lib/bundler/runtime.rb
   69 /usr/ruby/1.9/lib/ruby/gems/1.9.1/gems/bundler-1.7.12/lib/bundler/index.rb
   70 /usr/ruby/1.9/lib/ruby/gems/1.9.1/gems/bundler-1.7.12/lib/bundler/remote_specification.rb
   71 /usr/ruby/1.9/lib/ruby/gems/1.9.1/gems/bundler-1.7.12/lib/bundler/dep_proxy.rb
   72 /usr/ruby/1.9/lib/ruby/gems/1.9.1/gems/bundler-1.7.12/lib/bundler/resolver.rb
   73 /usr/ruby/1.9/lib/ruby/gems/1.9.1/gems/bundler-1.7.12/lib/bundler/endpoint_specification.rb
   74 /usr/ruby/1.9/lib/ruby/gems/1.9.1/gems/bundler-1.7.12/lib/bundler/ui.rb
   75 /usr/ruby/1.9/lib/ruby/gems/1.9.1/gems/bundler-1.7.12/lib/bundler/ui/silent.rb
   76 /usr/ruby/1.9/lib/ruby/1.9.1/rubygems/source_index.rb
   77 /usr/ruby/1.9/lib/ruby/gems/1.9.1/gems/bundler-1.7.12/lib/bundler/setup.rb
   78 /usr/ruby/1.9/lib/ruby/1.9.1/e2mmap.rb
   79 /usr/ruby/1.9/lib/ruby/1.9.1/irb/init.rb
   80 /usr/ruby/1.9/lib/ruby/1.9.1/irb/workspace.rb
   81 /usr/ruby/1.9/lib/ruby/1.9.1/irb/inspector.rb
   82 /usr/ruby/1.9/lib/ruby/1.9.1/irb/context.rb
   83 /usr/ruby/1.9/lib/ruby/1.9.1/irb/extend-command.rb
   84 /usr/ruby/1.9/lib/ruby/1.9.1/irb/output-method.rb
   85 /usr/ruby/1.9/lib/ruby/1.9.1/irb/notifier.rb
   86 /usr/ruby/1.9/lib/ruby/1.9.1/irb/slex.rb
   87 /usr/ruby/1.9/lib/ruby/1.9.1/irb/ruby-token.rb
   88 /usr/ruby/1.9/lib/ruby/1.9.1/irb/ruby-lex.rb
   89 /usr/ruby/1.9/lib/ruby/1.9.1/irb/src_encoding.rb
   90 /usr/ruby/1.9/lib/ruby/1.9.1/irb/magic-file.rb
   91 /usr/ruby/1.9/lib/ruby/1.9.1/amd64-solaris2.11/readline.so
   92 /usr/ruby/1.9/lib/ruby/1.9.1/irb/input-method.rb
   93 /usr/ruby/1.9/lib/ruby/1.9.1/irb/locale.rb
   94 /usr/ruby/1.9/lib/ruby/1.9.1/irb.rb
   95 /export/home/aaron/eventmachine/lib/rubyeventmachine.so
   96 /export/home/aaron/eventmachine/lib/em/pool.rb
   97 /export/home/aaron/eventmachine/lib/em/deferrable.rb
   98 /export/home/aaron/eventmachine/lib/em/future.rb
   99 /export/home/aaron/eventmachine/lib/em/streamer.rb
  100 /export/home/aaron/eventmachine/lib/em/spawnable.rb
  101 /export/home/aaron/eventmachine/lib/em/processes.rb
  102 /export/home/aaron/eventmachine/lib/em/iterator.rb
  103 /export/home/aaron/eventmachine/lib/em/buftok.rb
  104 /export/home/aaron/eventmachine/lib/em/timers.rb
  105 /export/home/aaron/eventmachine/lib/em/protocols.rb
  106 /export/home/aaron/eventmachine/lib/em/connection.rb
  107 /export/home/aaron/eventmachine/lib/em/callback.rb
  108 /export/home/aaron/eventmachine/lib/em/queue.rb
  109 /export/home/aaron/eventmachine/lib/em/channel.rb
  110 /export/home/aaron/eventmachine/lib/em/file_watch.rb
  111 /export/home/aaron/eventmachine/lib/em/process_watch.rb
  112 /export/home/aaron/eventmachine/lib/em/tick_loop.rb
  113 /export/home/aaron/eventmachine/lib/em/resolver.rb
  114 /export/home/aaron/eventmachine/lib/em/completion.rb
  115 /export/home/aaron/eventmachine/lib/em/threaded_resource.rb
  116 /usr/ruby/1.9/lib/ruby/1.9.1/shellwords.rb
  117 /usr/ruby/1.9/lib/ruby/1.9.1/amd64-solaris2.11/socket.so
  118 /usr/ruby/1.9/lib/ruby/1.9.1/socket.rb
  119 /usr/ruby/1.9/lib/ruby/1.9.1/amd64-solaris2.11/fcntl.so
  120 /usr/ruby/1.9/lib/ruby/1.9.1/timeout.rb
  121 /usr/ruby/1.9/lib/ruby/1.9.1/amd64-solaris2.11/openssl.so
  122 /usr/ruby/1.9/lib/ruby/1.9.1/openssl/bn.rb
  123 /usr/ruby/1.9/lib/ruby/1.9.1/openssl/cipher.rb
  124 /usr/ruby/1.9/lib/ruby/1.9.1/amd64-solaris2.11/stringio.so
  125 /usr/ruby/1.9/lib/ruby/1.9.1/openssl/config.rb
  126 /usr/ruby/1.9/lib/ruby/1.9.1/openssl/digest.rb
  127 /usr/ruby/1.9/lib/ruby/1.9.1/openssl/buffering.rb
  128 /usr/ruby/1.9/lib/ruby/1.9.1/openssl/ssl-internal.rb
  129 /usr/ruby/1.9/lib/ruby/1.9.1/openssl/x509-internal.rb
  130 /usr/ruby/1.9/lib/ruby/1.9.1/openssl.rb
  131 /usr/ruby/1.9/lib/ruby/1.9.1/securerandom.rb
  132 /usr/ruby/1.9/lib/ruby/1.9.1/resolv.rb
  133 /export/home/aaron/eventmachine/lib/eventmachine.rb

[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
For details: http://www.ruby-lang.org/bugreport.html
```

**Comment by sodabrew** [comment]
The problem appears to be stack corruption.
`EM.connect_server` calls `t_connect_server`
`t_connect_server` calls `evma_connect_to_server`
`evma_connect_to_server` wraps a `try-catch` around `EventMachine->ConnectToServer`
`ConnectToServer` calls `name2address`

`name2address` fails to find the hostname, so it returns NULL.
`ConnectToServer` checks the return value, sees NULL, and then throws `std::runtime_error ("unable to resolve server address");`

It blows up while unwinding the stack from ConnectToServer back to evma_connect_to_server.

If I change ConnectToServer to return 0 instead of throwing std::runtime_error, it errors cleanly back into the user's Ruby script as on Linux.

**Comment by sodabrew** [comment]
It turns out the minimum repro case does not even involve gethostbyname, etc. This will do the trick in a C++ method that is called from Ruby:

`try { throw std::runtime_error ("foo"); } catch (std::runtime_error e) { it crashes before getting here. }`
