### ISSUE TITLE
`synchronize': can't be called from trap context (ThreadError)

### ISSUE THREAD

**Issue by abonec** [eventmachine/eventmachine#418]
In ruby 2.0 I can't use trap for debugging EM in development mode.
I use this snippet:

``` ruby
require 'eventmachine'
EM.run do
  trap("INT") {EM.defer { puts 'start debugging with pry' }}
end
```

It work in 1.9.3 but don't work in 2.0.

May be it is wrong way and is there better approaches to inspect launched EM?

**Comment by rblakeley** [comment]
Getting the same thing in Foreman:

```
[12:57:01] :: foreman start
12:57:01 web.1  | started with pid 1812
^CSIGINT received
/usr/local/foreman/lib/foreman/engine.rb:226:in `synchronize': can't be called from trap context (ThreadError)
	from /usr/local/foreman/lib/foreman/engine.rb:226:in `output_with_mutex'
	from /usr/local/foreman/lib/foreman/engine.rb:232:in `system'
	from /usr/local/foreman/lib/foreman/engine.rb:304:in `terminate_gracefully'
	from /usr/local/foreman/lib/foreman/engine.rb:41:in `block in start'
```

**Comment by sodabrew** [comment]
This is very much related to the classic Unix FAQ: "What functions are safe in a signal handler?"

It looks like Ruby < 2.0 allowed a number of unsafe things, while 2.0 is disallowing them. Is there something we should do in eventmachine to help prevent these from happening? For example, should we wrap `trap` e.g `EM.trap(signum)`?

... as it happens, this was suggested in #97

**Comment by AddySridhar95** [comment]
This helped me: https://github.com/ddollar/foreman/issues/448
