### ISSUE TITLE
NoMethodError in JRuby/Puma with Faye

### ISSUE THREAD

**Issue by dwbutler** [eventmachine/eventmachine#494]
Hi,

We're using Faye::Redis in Puma/JRuby, which uses em-hiredis. We're seeing some intermittent errors (see below for full backtraces). Any advice?

``` ruby
NoMethodError: undefined method `connect_unix_server' for EventMachine:Module
…y/1.9/gems/eventmachine-1.0.3-java/lib/eventmachine.rb: 667:in `bind_connect'
…y/1.9/gems/eventmachine-1.0.3-java/lib/eventmachine.rb: 640:in `connect'
….9/gems/em-hiredis-0.2.1/lib/em-hiredis/base_client.rb:  59:in `connect'
…ndle/jruby/1.9/gems/em-hiredis-0.2.1/lib/em-hiredis.rb:  39:in `connect'
…ndle/jruby/1.9/gems/faye-redis-0.2.0/lib/faye/redis.rb:  35:in `init'
…ndle/jruby/1.9/gems/faye-redis-0.2.0/lib/faye/redis.rb:  64:in `create_client'
…/jruby/1.9/gems/faye-1.0.1/lib/faye/protocol/server.rb: 170:in `handshake'
…/jruby/1.9/gems/faye-1.0.1/lib/faye/protocol/server.rb: 117:in `handle_meta'
…/jruby/1.9/gems/faye-1.0.1/lib/faye/protocol/server.rb:  91:in `handle'
…/jruby/1.9/gems/faye-1.0.1/lib/faye/protocol/server.rb:  67:in `process'
```

``` ruby
NoMethodError: undefined method `installOneshotTimer' for nil:NilClass
…/1.9/gems/eventmachine-1.0.3-java/lib/jeventmachine.rb: 108:in `add_oneshot_timer'
…y/1.9/gems/eventmachine-1.0.3-java/lib/eventmachine.rb: 323:in `add_timer'
…ruby/1.9/gems/eventmachine-1.0.3-java/lib/em/timers.rb:  12:in `initialize'
…/1.9/gems/eventmachine-1.0.3-java/lib/em/deferrable.rb: 173:in `timeout'
…ruby/1.9/gems/faye-1.0.1/lib/faye/protocol/envelope.rb:  11:in `initialize'
```

``` ruby
NoMethodError: undefined method `attachChannel' for nil:NilClass
…/1.9/gems/eventmachine-1.0.3-java/lib/jeventmachine.rb: 246:in `attach_fd'
…y/1.9/gems/eventmachine-1.0.3-java/lib/eventmachine.rb: 745:in `attach_io'
…y/1.9/gems/eventmachine-1.0.3-java/lib/eventmachine.rb: 728:in `attach'
…/1.9/gems/faye-websocket-0.7.2/lib/faye/rack_stream.rb:  26:in `initialize'
…by/1.9/gems/faye-websocket-0.7.2/lib/faye/websocket.rb:  70:in `initialize'
…/1.9/gems/faye-1.0.1/lib/faye/adapters/rack_adapter.rb: 159:in `handle_websocket'
```

**Comment by film42** [comment]
Same here!

**Comment by sodabrew** [comment]
These methods should be available in the eventmachine 1.0.3 Java implementation, but I would recommend updating to a newer version of eventmachine as the Java implementation has been improved and bug-fixed a bit recently.

**Comment by film42** [comment]
@sodabrew I was getting the following error with version `1.0.7`:

```
2015-08-14 09:52:16 -0600: Rack app error: #<NoMethodError: undefined method `attachChannel' for nil:NilClass>
/srv/app/shared/bundle/jruby/1.9/gems/eventmachine-1.0.7-java/lib/jeventmachine.rb:246:in `attach_fd'
/srv/app/shared/bundle/jruby/1.9/gems/eventmachine-1.0.7-java/lib/eventmachine.rb:754:in `attach_io'
/srv/app/shared/bundle/jruby/1.9/gems/eventmachine-1.0.7-java/lib/eventmachine.rb:737:in `attach'
/srv/app/shared/bundle/jruby/1.9/gems/faye-websocket-0.10.0/lib/faye/rack_stream.rb:26:in `initialize'
/srv/app/shared/bundle/jruby/1.9/gems/faye-websocket-0.10.0/lib/faye/websocket.rb:70:in `initialize'
/srv/app/shared/bundle/jruby/1.9/gems/faye-1.1.2/lib/faye/adapters/rack_adapter.rb:192:in `handle_websocket'
/srv/app/shared/bundle/jruby/1.9/gems/faye-1.1.2/lib/faye/adapters/rack_adapter.rb:92:in `call'
faye.ru:31:in `call'
/srv/app/shared/bundle/jruby/1.9/gems/puma-2.11.3-java/lib/puma/configuration.rb:51:in `call'
/srv/app/shared/bundle/jruby/1.9/gems/puma-2.11.3-java/lib/puma/server.rb:507:in `handle_request'
/srv/app/shared/bundle/jruby/1.9/gems/puma-2.11.3-java/lib/puma/server.rb:505:in `handle_request'
/srv/app/shared/bundle/jruby/1.9/gems/puma-2.11.3-java/lib/puma/server.rb:375:in `process_client'
/srv/app/shared/bundle/jruby/1.9/gems/puma-2.11.3-java/lib/puma/server.rb:371:in `process_client'
/srv/app/shared/bundle/jruby/1.9/gems/puma-2.11.3-java/lib/puma/server.rb:262:in `run'
```

This error only seems to happen after running correctly for a while. My best guess is that we're running out of file descriptors. We're seeing a large amount of half open sockets:

```
$ sudo lsof | grep $(pgrep -f faye) | grep "can"
java       4162          deployer   77u     sock                0,7      0t0   42003976 can't identify protocol
java       4162          deployer   80u     sock                0,7      0t0   42006315 can't identify protocol
java       4162          deployer   81u     sock                0,7      0t0   42004555 can't identify protocol
java       4162          deployer   82u     sock                0,7      0t0   42004560 can't identify protocol
...
```

This is using puma to start faye. This could be more of a Faye related issue, and the two problems might not be correlated, but I thought I'd add this as evidence. Btw, in this lsof dump, the pid 4162 is the puma process (just to be clear).

**Comment by sodabrew** [comment]
My fault, I didn't read the part about undefined method _for nil_. Yes, it sounds like there's a missing check against a nil result when getting a file handle. The Ruby layer may be expecting a call to succeed or raise an exception, but not to return nil. I'll take a look for where this might be happening.

**Comment by sodabrew** [comment]
The errant line is in lib/jeventmachine.rb, method `attach_fd`: `@em.attachChannel`. For `@em` to be nil, either the method was called before `initialize_event_machine`, which is called from `EM.run`, or called after a `release_machine`. There are calls to `release_machine` at the top of `EM.run`.

Puma is a threaded server, is it trying to run more than one EM on different threads?
