### ISSUE TITLE
`unbind': wrong number of arguments (1 for 0) (ArgumentError) when forwarded via def_delegators

### ISSUE THREAD

**Issue by egwspiti** [eventmachine/eventmachine#526]
``` ruby
require 'eventmachine'
require 'forwardable'

class X < EM::Connection
  extend Forwardable
  def_delegators :@client, :connection_completed, :unbind

  def initialize(client)
    @client = client
  end
end

class Client
  def connection_completed
    puts 'connected'
  end

  def unbind
    puts 'disconnected'
  end

  def run
    EM.run do
      EM::connect('localhost', 3333, X, self)
    end
  end

end

Client.new.run
```

When excecuted with nothing listening at localhost:3333, it fails with:

```
em.rb:18:in `unbind': wrong number of arguments (1 for 0) (ArgumentError)
         from .../gems/eventmachine-1.0.3/lib/eventmachine.rb:1438:in `event_callback'
         from .../gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run_machine'
         from .../gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run'
         from em.rb:23:in `run'
         from em.rb:30:in `<main>'
```

Moving `unbind` back to class X makes it work as expected.

**Comment by sodabrew** [comment]
I don't know what to do with this bug report.
Is there a fix you would like to see in the eventmachine codebase?
