### ISSUE TITLE
test_dispatch_completion(TestThreadedResource) timeouts randomly

### ISSUE THREAD

**Issue by voxik** [eventmachine/eventmachine#580]
I randomly observe test_dispatch_completion(TestThreadedResource) on my Fedora Rawhide, running the test suite with Ruby 2.2:

~~~
Error: test_dispatch_completion(TestThreadedResource)
: RuntimeError: Resource dispatch timed out
/builddir/build/BUILD/rubygem-eventmachine-1.0.6/usr/share/gems/gems/eventmachine-1.0.6/tests/test_threaded_resource.rb:20:in `block (2 levels) in test_dispatch_completion'
     17:     EM.run do
     18:       EM.add_timer(3) do
     19:         EM.stop
  => 20:         fail 'Resource dispatch timed out'
     21:       end
     22:       completion = resource.dispatch do |o|
     23:         o[:foo] = :bar
/builddir/build/BUILD/rubygem-eventmachine-1.0.6/usr/share/gems/gems/eventmachine-1.0.6/lib/eventmachine.rb:187:in `call'
/builddir/build/BUILD/rubygem-eventmachine-1.0.6/usr/share/gems/gems/eventmachine-1.0.6/lib/eventmachine.rb:187:in `run_machine'
/builddir/build/BUILD/rubygem-eventmachine-1.0.6/usr/share/gems/gems/eventmachine-1.0.6/lib/eventmachine.rb:187:in `run'
/builddir/build/BUILD/rubygem-eventmachine-1.0.6/usr/share/gems/gems/eventmachine-1.0.6/tests/test_threaded_resource.rb:17:in `test_dispatch_completion'
~~~

**Comment by sodabrew** [comment]
Yep, got this tracked in #575.

**Comment by voxik** [comment]
Ups, sorry for the noise. I'm closing this.
