### ISSUE TITLE
Error on start_server with ipv6 under Windows

### ISSUE THREAD

**Issue by topac** [eventmachine/eventmachine#595]
If I try to start a server passing "::1" as the host to bind to I get an error.

```ruby
EventMachine.run {
  EventMachine.start_server "::1", 8081, EchoServer
}
```
throws

```
C:/Ruby/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.7/lib/eventmachine.rb:526:in `start_tcp_server': no acceptor (port
 is in use or requires root privileges) (RuntimeError)
        from C:/Ruby/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.7/lib/eventmachine.rb:526:in `start_server'
        from ./echoserver2.rb:20:in `block in <main>'
        from C:/Ruby/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.7/lib/eventmachine.rb:187:in `call'
        from C:/Ruby/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.7/lib/eventmachine.rb:187:in `run_machine'
        from C:/Ruby/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.7/lib/eventmachine.rb:187:in `run'
```

**Comment by sodabrew** [comment]
See #630 for an implementation, feedback appreciated!
