### ISSUE TITLE
Stack level too deep in smtpserver v1.0.7

### ISSUE THREAD

**Issue by kjg** [eventmachine/eventmachine#608]
I occasionally see a stack level too deep error in the smtpserver on line :570 I'm not exactly what causes this, because once the process is restarted, the upstream server re-sends the message that was in transit at failure time and everything succeeds at that point.

The smtpserver process is receiving about 15 emails/second when this crash happens

```
vendor/bundle/ruby/2.2.0/gems/eventmachine-1.0.7/lib/em/protocols/smtpserver.rb:570:in `process_data_line': stack level too deep (SystemStackError)
	from vendor/bundle/ruby/2.2.0/gems/eventmachine-1.0.7/lib/em/protocols/smtpserver.rb:196:in `receive_line'
	from vendor/bundle/ruby/2.2.0/gems/eventmachine-1.0.7/lib/em/protocols/linetext2.rb:63:in `receive_data'
	from vendor/bundle/ruby/2.2.0/gems/eventmachine-1.0.7/lib/em/protocols/linetext2.rb:64:in `receive_data'
	from vendor/bundle/ruby/2.2.0/gems/eventmachine-1.0.7/lib/em/protocols/linetext2.rb:64:in `receive_data'
	from vendor/bundle/ruby/2.2.0/gems/eventmachine-1.0.7/lib/em/protocols/linetext2.rb:64:in `receive_data'
	from vendor/bundle/ruby/2.2.0/gems/eventmachine-1.0.7/lib/em/protocols/linetext2.rb:64:in `receive_data'
	from vendor/bundle/ruby/2.2.0/gems/eventmachine-1.0.7/lib/em/protocols/linetext2.rb:64:in `receive_data'
	from vendor/bundle/ruby/2.2.0/gems/eventmachine-1.0.7/lib/em/protocols/linetext2.rb:64:in `receive_data'
	 ... 6885 levels...
	from vendor/bundle/ruby/2.2.0/gems/eventmachine-1.0.7/lib/em/protocols/linetext2.rb:64:in `receive_data'
	from vendor/bundle/ruby/2.2.0/gems/eventmachine-1.0.7/lib/eventmachine.rb:187:in `run_machine'
	from vendor/bundle/ruby/2.2.0/gems/eventmachine-1.0.7/lib/eventmachine.rb:187:in `run'
```

Any idea what might be causing this, or what I can do to work around it?

**Comment by kjg** [comment]
```
      # Will be called recursively until there's no data to read.
      # That way the user-defined handlers we call can modify the
      # handling characteristics on a per-token basis.
      #
      def receive_data data
```

Is this just because a single connection is going on for too long!? If so, how can I combat that?

**Comment by sodabrew** [comment]
I haven't looked at this module carefully, but if it's using SMTP pipelining then it would make sense that this recursive call gets too deep after a while. Modifications welcome to make this iterative instead of recursive.
