### ISSUE TITLE
Mac El capital cannot install eventmachine

### ISSUE THREAD

**Issue by TommySAAS** [eventmachine/eventmachine#663]
Hi guys, I recently upgraded to El Capital OS on Mac and when I try to install websocket-rails gem this error came up. 

```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /Users/tommyngo/.rbenv/versions/2.1.5/bin/ruby -r ./siteconf20151210-19333-187glp6.rb extconf.rb
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/tommyngo/.rbenv/versions/2.1.5/bin/ruby
	--with-openssl-config
	--without-openssl-config
	--with-pkg-config
	--without-pkg-config
/Users/tommyngo/.rbenv/versions/2.1.5/lib/ruby/2.1.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /Users/tommyngo/.rbenv/versions/2.1.5/lib/ruby/2.1.0/mkmf.rb:541:in `try_link0'
	from /Users/tommyngo/.rbenv/versions/2.1.5/lib/ruby/2.1.0/mkmf.rb:556:in `try_link'
	from /Users/tommyngo/.rbenv/versions/2.1.5/lib/ruby/2.1.0/mkmf.rb:642:in `block in try_ldflags'
	from /Users/tommyngo/.rbenv/versions/2.1.5/lib/ruby/2.1.0/mkmf.rb:635:in `with_ldflags'
	from /Users/tommyngo/.rbenv/versions/2.1.5/lib/ruby/2.1.0/mkmf.rb:641:in `try_ldflags'
	from /Users/tommyngo/.rbenv/versions/2.1.5/lib/ruby/2.1.0/mkmf.rb:1762:in `pkg_config'
	from extconf.rb:64:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /Users/tommyngo/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/eventmachine-1.0.8 for inspection.
Results logged to /Users/tommyngo/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/extensions/x86_64-darwin-14/2.1.0-static/eventmachine-1.0.8/gem_make.out
An error occurred while installing eventmachine (1.0.8), and Bundler cannot
continue.
Make sure that `gem install eventmachine -v '1.0.8'` succeeds before bundling.
```

I have installed OpenSSL and tried `brew link --force openssl`. I have no idea what is going on. Could anyone please have a look at it?

**Comment by TommySAAS** [comment]
turn out I had to install Xcode. Problem is now solved

**Comment by sodabrew** [comment]
You may need to accept the license for XCode. Try `xcode-select --install` at a Terminal prompt.
