### ISSUE TITLE
On OS X, test_fork_reactor gets mismatched Process.pid encoding and value

### ISSUE THREAD

**Issue by sodabrew** [eventmachine/eventmachine#672]
This happens on Travis a lot, but I cannot reproduce it locally:

```
TestFork: 
  test_fork_reactor:                    F
===============================================================================
Failure:
test_fork_reactor(TestFork)
/Users/travis/build/eventmachine/eventmachine/tests/test_fork.rb:63:in `block in test_fork_reactor'
/Users/travis/.rvm/rubies/ruby-2.0.0-p643/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
/Users/travis/build/eventmachine/eventmachine/tests/test_fork.rb:62:in `test_fork_reactor'
     59: 
     60:     sleep 0.1
     61:     begin
  => 62:       Timeout::timeout 1 do
     63:         assert_equal Process.pid.to_s, read.readline.chomp
     64:         assert_equal fork_pid.to_s, read.readline.chomp
     65:       end
<"1273">(US-ASCII) expected but was
<"1282">(UTF-8)
diff:
? 1273
?   82

? Encoding: US -ASCII
?            TF 8    
===============================================================================
```

**Comment by sodabrew** [comment]
No longer happening on Travis CI. Closing.
