### ISSUE TITLE
Conflict with rvm - leads to linking against native system Ruby install

### ISSUE THREAD

**Issue by wtfiwtz** [eventmachine/eventmachine#692]
Recently installed Rack 2.0 alpha due to Rails 5, and this broke my existing script to run Thin as a static web server for a different (Java) project.

```
/Users/wtfiwtz/.rvm/gems/ruby-2.2.3/gems/eventmachine-1.0.8/lib/eventmachine.rb:8:in `require': incompatible library version - /Users/wtfiwtz/.rvm/gems/ruby-2.2.3/gems/eventmachine-1.0.8/lib/rubyeventmachine.bundle (fatal)
	from /Users/wtfiwtz/.rvm/gems/ruby-2.2.3/gems/eventmachine-1.0.8/lib/eventmachine.rb:8:in `<top (required)>'
	from /Users/wtfiwtz/.rvm/gems/ruby-2.2.3/bundler/gems/thin-84ae79de5492/lib/thin.rb:7:in `require'
	from /Users/wtfiwtz/.rvm/gems/ruby-2.2.3/bundler/gems/thin-84ae79de5492/lib/thin.rb:7:in `<top (required)>'
	from /Users/wtfiwtz/.rvm/gems/ruby-2.2.3/gems/bundler-1.10.6/lib/bundler/runtime.rb:76:in `require'
	from /Users/wtfiwtz/.rvm/gems/ruby-2.2.3/gems/bundler-1.10.6/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
	from /Users/wtfiwtz/.rvm/gems/ruby-2.2.3/gems/bundler-1.10.6/lib/bundler/runtime.rb:72:in `each'
	from /Users/wtfiwtz/.rvm/gems/ruby-2.2.3/gems/bundler-1.10.6/lib/bundler/runtime.rb:72:in `block in require'
	from /Users/wtfiwtz/.rvm/gems/ruby-2.2.3/gems/bundler-1.10.6/lib/bundler/runtime.rb:61:in `each'
	from /Users/wtfiwtz/.rvm/gems/ruby-2.2.3/gems/bundler-1.10.6/lib/bundler/runtime.rb:61:in `require'
	from /Users/wtfiwtz/.rvm/gems/ruby-2.2.3/gems/bundler-1.10.6/lib/bundler.rb:134:in `require'
	from /Developer/images.rb:5:in `<main>'
```

`gem cleanup` followed by `gem pristine --all` didn't solve it.

Using `otool -L` I was able to establish that the .bundle file was linked to the native Ruby 2.0 library on Mac OS X, and not using the rvm version of ruby (2.2.3).

Using this worked:
`gem install eventmachine -v 1.0.8 -- --with-ruby-lib=/Users/wtfiwtz/.rvm/rubies/ruby-2.2.3/lib/`

Just popping this up here in case it helps someone else.

Cheers, @wtfiwtz

**Comment by sodabrew** [comment]
Thanks for sharing! Is there some change that the eventmachine build process should include to handle this case automatically?

**Comment by wtfiwtz** [comment]
I don't think so... having a look here:

https://github.com/eventmachine/eventmachine/blob/master/ext/extconf.rb#L200

It might be that I could have also mucked around with the LDCONFIG environmental variable as another solution. Perhaps the library order is dependent on what you have installed. The actual library paths look empty and very little shows up in -v:

```
Nigel-MBP:tor-photos wtfiwtz$ gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin15.3.0
Thread model: posix
Nigel-MBP:tor-photos wtfiwtz$ g++ -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin15.3.0
Thread model: posix
Nigel-MBP:tor-photos wtfiwtz$ ld -v
@(#)PROGRAM:ld  PROJECT:ld64-253.9
configured to support archs: armv6 armv7 armv7s arm64 i386 x86_64 x86_64h armv6m armv7k armv7m armv7em (tvOS)
LTO support using: Apple LLVM 7.0.2 (clang-700.1.81)
```

This is what the man page for `ld` says on El Capitan:
```
   Search paths
     ld maintains a list of directories to search for a library or framework
     to use.  The default library search path is /usr/lib then /usr/local/lib.
     The -L option will add a new library search path.  The default framework
     search path is /Library/Frameworks then /System/Library/Frameworks.
     (Note: previously, /Network/Library/Frameworks was at the end of the
     default path.  If you need that functionality, you need to explicitly add
     -F/Network/Library/Frameworks).  The -F option will add a new framework
     search path.  The -Z option will remove the standard search paths.  The
     -syslibroot option will prepend a prefix to all search paths.

```
I've managed to get `eventmachine` installed okay at other times on Mac OS X, even more recently than this issue, but perhaps they were different versions. The difference could be that this one didn't use the `bundler` gem but I'm not sure.
