### ISSUE TITLE
El Capital OS X 10.11 with Xcode Version 7.3 (7D175) Failed to build gem native extension.

### ISSUE THREAD

**Issue by paulz** [eventmachine/eventmachine#713]
```
Installing eventmachine 1.2.0.1 with native extensions

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    ~/.rvm/rubies/ruby-2.2.3/bin/ruby -r ./siteconf20160418-27570-tb5r0r.rb extconf.rb
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=~/.rvm/rubies/ruby-2.2.3/bin/$(RUBY_BASE_NAME)
	--with-ssl-dir
	--without-ssl-dir
	--with-ssl-include
	--without-ssl-include=${ssl-dir}/include
	--with-ssl-lib
	--without-ssl-lib=${ssl-dir}/lib
	--with-openssl-config
	--without-openssl-config
	--with-pkg-config
	--without-pkg-config
~/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from ~/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/mkmf.rb:541:in `try_link0'
	from ~/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/mkmf.rb:556:in `try_link'
	from ~/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/mkmf.rb:637:in `try_ldflags'
	from ~/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/mkmf.rb:1780:in `pkg_config'
	from extconf.rb:65:in `pkg_config_wrapper'
	from extconf.rb:92:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in ~/.rvm/gems/ruby-2.2.3@twilio-sms-forward/gems/eventmachine-1.2.0.1 for inspection.
Results logged to ~/.rvm/gems/ruby-2.2.3@twilio-sms-forward/extensions/x86_64-darwin-15/2.2.0/eventmachine-1.2.0.1/gem_make.out
```

```
xcode-select --install
xcode-select: error: command line tools are already installed, use "Software Update" to install updates
```

```
brew info openssl
openssl: stable 1.0.2g (bottled) [keg-only]
SSL/TLS cryptography library
https://openssl.org/
/usr/local/Cellar/openssl/1.0.2e (1,646 files, 11.9M)
  Poured from bottle
/usr/local/Cellar/openssl/1.0.2e_1 (1,646 files, 11.9M)
  Poured from bottle
/usr/local/Cellar/openssl/1.0.2g (1,678 files, 12.0M) *
  Poured from bottle
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/openssl.rb
==> Dependencies
Build: makedepend ✔
==> Options
--universal
	Build a universal binary
--without-test
	Skip build-time tests (not recommended)
==> Caveats
A CA file has been bootstrapped using certificates from the system
keychain. To add additional certificates, place .pem files in
  /usr/local/etc/openssl/certs

and run
  /usr/local/opt/openssl/bin/c_rehash

This formula is keg-only, which means it was not symlinked into /usr/local.

Apple has deprecated use of OpenSSL in favor of its own TLS and crypto libraries

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/openssl/lib
    CPPFLAGS: -I/usr/local/opt/openssl/include


```

**Comment by sodabrew** [comment]
Take a look in `~/.rvm/gems/ruby-2.2.3@twilio-sms-forward/extensions/x86_64-darwin-15/2.2.0/eventmachine-1.2.0.1/gem_make.out` to see where it reports the underlying compiler error.

**Comment by paulz** [comment]
~/.rvm/gems/ruby-2.2.3@twilio-sms-forward/extensions/x86_64-darwin-15/2.2.0/eventmachine-1.2.0.1/gem_make.out
```
~/.rvm/rubies/ruby-2.2.3/bin/ruby -r ./siteconf20160418-56794-fk9k17.rb extconf.rb
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=~/.rvm/rubies/ruby-2.2.3/bin/$(RUBY_BASE_NAME)
	--with-ssl-dir
	--without-ssl-dir
	--with-ssl-include
	--without-ssl-include=${ssl-dir}/include
	--with-ssl-lib
	--without-ssl-lib=${ssl-dir}/lib
	--with-openssl-config
	--without-openssl-config
	--with-pkg-config
	--without-pkg-config
~/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from ~/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/mkmf.rb:541:in `try_link0'
	from ~/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/mkmf.rb:556:in `try_link'
	from ~/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/mkmf.rb:637:in `try_ldflags'
	from ~/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/mkmf.rb:1780:in `pkg_config'
	from extconf.rb:65:in `pkg_config_wrapper'
	from extconf.rb:92:in `<main>'

extconf failed, exit code 1
```

**Comment by paulz** [comment]
The error message suggests to take a looks at this file: `~/.rvm/gems/ruby-2.2.3@twilio-sms-forward/extensions/x86_64-darwin-15/2.2.0/eventmachine-1.2.0.1/mkmf.log`

which oddly enough complains about `error: unknown type name 'ruby'`:

```
"gcc -o conftest -I~/.rvm/rubies/ruby-2.2.3/include/ruby-2.2.0/x86_64-darwin15 -I~/.rvm/rubies/ruby-2.2.3/include/ruby-2.2.0/ruby/backward -I~/.rvm/rubies/ruby-2.2.3/include/ruby-2.2.0 -I.  -I/usr/local/opt/libyaml/include -I/usr/local/opt/readline/include -I/usr/local/opt/libksba/include -I/usr/local/opt/openssl/include -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT    -O3 -fno-fast-math -ggdb3 -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Wunused-variable -Wpointer-arith -Wwrite-strings -Wdeclaration-after-statement -Wshorten-64-to-32 -Wimplicit-function-declaration -Wdivision-by-zero -Wdeprecated-declarations -Wextra-tokens  -fno-common -pipe conftest.c  -L/usr/local/opt/libyaml/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/libksba/lib -L/usr/local/opt/openssl/lib -L. -L~/.rvm/rubies/ruby-2.2.3/lib -L. -fstack-protector -L/usr/local/opt/libyaml/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/libksba/lib -L/usr/local/opt/openssl/lib      -lruby.2.2.0  -lpthread -ldl -lobjc "
In file included from conftest.c:1:
~/.rvm/rubies/ruby-2.2.3/include/ruby-2.2.0/ruby.h:1:3: error: unknown type name 'ruby'
  ruby.h -
  ^
~/.rvm/rubies/ruby-2.2.3/include/ruby-2.2.0/ruby.h:1:7: error: expected identifier or '('
  ruby.h -
      ^
In file included from conftest.c:1:
In file included from ~/.rvm/rubies/ruby-2.2.3/include/ruby-2.2.0/ruby.h:31:
In file included from ~/.rvm/rubies/ruby-2.2.3/include/ruby-2.2.0/ruby/ruby.h:27:
In file included from ~/.rvm/rubies/ruby-2.2.3/include/ruby-2.2.0/ruby/defines.h:66:
~/.rvm/rubies/ruby-2.2.3/include/ruby-2.2.0/ruby/missing.h:1:3: error: unknown type name 'missing'
  missing.h - prototype for *.c in ./missing, and
  ^
~/.rvm/rubies/ruby-2.2.3/include/ruby-2.2.0/ruby/missing.h:1:10: error: expected identifier or '('
  missing.h - prototype for *.c in ./missing, and
         ^
~/.rvm/rubies/ruby-2.2.3/include/ruby-2.2.0/ruby/missing.h:45:5: error: unknown type name 'time_t'; did you mean 'size_t'?
    time_t tv_sec;      /* seconds */
    ^~~~~~
    size_t
/usr/include/sys/_types/_size_t.h:30:32: note: 'size_t' declared here
typedef __darwin_size_t        size_t; 
                               ^
In file included from conftest.c:1:
In file included from ~/.rvm/rubies/ruby-2.2.3/include/ruby-2.2.0/ruby.h:31:
In file included from ~/.rvm/rubies/ruby-2.2.3/include/ruby-2.2.0/ruby/ruby.h:27:
In file included from ~/.rvm/rubies/ruby-2.2.3/include/ruby-2.2.0/ruby/defines.h:66:
~/.rvm/rubies/ruby-2.2.3/include/ruby-2.2.0/ruby/missing.h:52:5: error: unknown type name 'time_t'; did you mean 'size_t'?
    time_t tv_sec;      /* seconds */
    ^~~~~~
    size_t
/usr/include/sys/_types/_size_t.h:30:32: note: 'size_t' declared here
typedef __darwin_size_t        size_t; 
                               ^
In file included from conftest.c:1:
In file included from ~/.rvm/rubies/ruby-2.2.3/include/ruby-2.2.0/ruby.h:31:
In file included from ~/.rvm/rubies/ruby-2.2.3/include/ruby-2.2.0/ruby/ruby.h:27:
In file included from ~/.rvm/rubies/ruby-2.2.3/include/ruby-2.2.0/ruby/defines.h:66:
~/.rvm/rubies/ruby-2.2.3/include/ruby-2.2.0/ruby/missing.h:220:17: error: expected identifier or '('
RUBY_EXTERN int signbit(double x);
                ^
/usr/include/math.h:184:7: note: expanded from macro 'signbit'
    ( sizeof(x) == sizeof(float)  ? __inline_signbitf((float)(x))        \
      ^
In file included from conftest.c:1:
In file included from ~/.rvm/rubies/ruby-2.2.3/include/ruby-2.2.0/ruby.h:31:
In file included from ~/.rvm/rubies/ruby-2.2.3/include/ruby-2.2.0/ruby/ruby.h:27:
In file included from ~/.rvm/rubies/ruby-2.2.3/include/ruby-2.2.0/ruby/defines.h:66:
~/.rvm/rubies/ruby-2.2.3/include/ruby-2.2.0/ruby/missing.h:220:17: error: expected ')'
/usr/include/math.h:184:7: note: expanded from macro 'signbit'
    ( sizeof(x) == sizeof(float)  ? __inline_signbitf((float)(x))        \
      ^
~/.rvm/rubies/ruby-2.2.3/include/ruby-2.2.0/ruby/missing.h:220:17: note: to match this '('
/usr/include/math.h:184:5: note: expanded from macro 'signbit'
    ( sizeof(x) == sizeof(float)  ? __inline_signbitf((float)(x))        \
    ^
In file included from conftest.c:1:
In file included from ~/.rvm/rubies/ruby-2.2.3/include/ruby-2.2.0/ruby.h:31:
~/.rvm/rubies/ruby-2.2.3/include/ruby-2.2.0/ruby/ruby.h:104:36: error: use of undeclared identifier 'SIZEOF_INT'
typedef char ruby_check_sizeof_int[SIZEOF_INT == sizeof(int) ? 1 : -1];
                                   ^
~/.rvm/rubies/ruby-2.2.3/include/ruby-2.2.0/ruby/ruby.h:105:37: error: use of undeclared identifier 'SIZEOF_LONG'
typedef char ruby_check_sizeof_long[SIZEOF_LONG == sizeof(long) ? 1 : -1];
                                    ^
~/.rvm/rubies/ruby-2.2.3/include/ruby-2.2.0/ruby/ruby.h:109:38: error: use of undeclared identifier 'SIZEOF_VOIDP'
typedef char ruby_check_sizeof_voidp[SIZEOF_VOIDP == sizeof(void*) ? 1 : -1];
                                     ^
~/.rvm/rubies/ruby-2.2.3/include/ruby-2.2.0/ruby/ruby.h:612:9: warning: implicit declaration of function 'RSHIFT' is invalid in C99 [-Wimplicit-function-declaration]
        return FIX2LONG(x);
               ^
~/.rvm/rubies/ruby-2.2.3/include/ruby-2.2.0/ruby/ruby.h:346:28: note: expanded from macro 'FIX2LONG'
#define FIX2LONG(x) ((long)RSHIFT((SIGNED_VALUE)(x),1))
                           ^
~/.rvm/rubies/ruby-2.2.3/include/ruby-2.2.0/ruby/ruby.h:1301:9: warning: comparison of constant 4611686018427387904 with expression of type 'int' is always true [-Wtautological-constant-out-of-range-compare]
    if (FIXABLE(v))
        ^~~~~~~~~~
~/.rvm/rubies/ruby-2.2.3/include/ruby-2.2.0/ruby/ruby.h:351:21: note: expanded from macro 'FIXABLE'
#define FIXABLE(f) (POSFIXABLE(f) && NEGFIXABLE(f))
                    ^~~~~~~~~~~~~
~/.rvm/rubies/ruby-2.2.3/include/ruby-2.2.0/ruby/ruby.h:349:28: note: expanded from macro 'POSFIXABLE'
#define POSFIXABLE(f) ((f) < FIXNUM_MAX+1)
                       ~~~ ^ ~~~~~~~~~~~~
~/.rvm/rubies/ruby-2.2.3/include/ruby-2.2.0/ruby/ruby.h:1311:9: warning: comparison of constant 4611686018427387904 with expression of type 'unsigned int' is always true [-Wtautological-constant-out-of-range-compare]
    if (POSFIXABLE(v))
        ^~~~~~~~~~~~~
~/.rvm/rubies/ruby-2.2.3/include/ruby-2.2.0/ruby/ruby.h:349:28: note: expanded from macro 'POSFIXABLE'
#define POSFIXABLE(f) ((f) < FIXNUM_MAX+1)
                       ~~~ ^ ~~~~~~~~~~~~
In file included from conftest.c:1:
In file included from ~/.rvm/rubies/ruby-2.2.3/include/ruby-2.2.0/ruby.h:31:
In file included from ~/.rvm/rubies/ruby-2.2.3/include/ruby-2.2.0/ruby/ruby.h:1708:
~/.rvm/rubies/ruby-2.2.3/include/ruby-2.2.0/ruby/intern.h:1:3: error: unknown type name 'intern'; did you mean 'extern'?
  intern.h -
  ^~~~~~
  extern
~/.rvm/rubies/ruby-2.2.3/include/ruby-2.2.0/ruby/intern.h:1:9: error: expected identifier or '('
  intern.h -
        ^
In file included from conftest.c:1:
In file included from ~/.rvm/rubies/ruby-2.2.3/include/ruby-2.2.0/ruby.h:31:
In file included from ~/.rvm/rubies/ruby-2.2.3/include/ruby-2.2.0/ruby/ruby.h:1708:
In file included from ~/.rvm/rubies/ruby-2.2.3/include/ruby-2.2.0/ruby/intern.h:30:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/7.3.0/include/varargs.h:25:4: error: "Please use <stdarg.h> instead of <varargs.h>"
  #error "Please use <stdarg.h> instead of <varargs.h>"
   ^
In file included from conftest.c:1:
In file included from ~/.rvm/rubies/ruby-2.2.3/include/ruby-2.2.0/ruby.h:31:
In file included from ~/.rvm/rubies/ruby-2.2.3/include/ruby-2.2.0/ruby/ruby.h:1708:
In file included from ~/.rvm/rubies/ruby-2.2.3/include/ruby-2.2.0/ruby/intern.h:33:
~/.rvm/rubies/ruby-2.2.3/include/ruby-2.2.0/ruby/st.h:46:9: error: unknown type name 'st_data_t'
typedef st_data_t st_index_t;
        ^
~/.rvm/rubies/ruby-2.2.3/include/ruby-2.2.0/ruby/st.h:47:40: error: redefinition of parameter 'st_data_t'
typedef int st_compare_func(st_data_t, st_data_t);
                                       ^
~/.rvm/rubies/ruby-2.2.3/include/ruby-2.2.0/ruby/st.h:47:29: error: a parameter list without types is only allowed in a function definition
typedef int st_compare_func(st_data_t, st_data_t);
                            ^
~/.rvm/rubies/ruby-2.2.3/include/ruby-2.2.0/ruby/st.h:48:33: error: a parameter list without types is only allowed in a function definition
typedef st_index_t st_hash_func(st_data_t);
                                ^
~/.rvm/rubies/ruby-2.2.3/include/ruby-2.2.0/ruby/st.h:50:45: error: use of undeclared identifier 'SIZEOF_VOIDP'
typedef char st_check_for_sizeof_st_index_t[SIZEOF_VOIDP == (int)sizeof(st_index_t) ? 1 : -1];
                                            ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
3 warnings and 20 errors generated.
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: int main(int argc, char **argv)
4: {
5:   return 0;
6: }
/* end */

```

**Comment by paulz** [comment]
Here is what helped me:
```
rvm install 2.3.0
rvm use 2.3.0 --default
```

**Comment by sodabrew** [comment]
Oh, sorry, I meant the `mkmf.log` file, that should have the underlying errors.
