### ISSUE TITLE
unable to resolve server address: Success

### ISSUE THREAD

**Issue by dgutov** [eventmachine/eventmachine#719]
```
irb(main):005:0> EM.run { EM.bind_connect(nil, nil, 'xxxxxx.co', 80); EM.stop }
EventMachine::ConnectionError: unable to resolve server address: Success
    from /home/gutov/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:677:in `connect_server'
    from /home/gutov/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:677:in `bind_connect'
    from (irb):5:in `block in irb_binding'
    from /home/gutov/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:194:in `call'
    from /home/gutov/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:194:in `run_machine'
    from /home/gutov/.rbenv/versions/1.9.3-p547/lib/ruby/gems/1.9.1/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:194:in `run'
    from (irb):5
    from /home/gutov/.rbenv/versions/1.9.3-p547/bin/irb:12:in `<main>'
irb(main):006:0> EventMachine::VERSION
=> "1.2.0.1"
```

I think it should report the hostname it couldn't resolve instead of "Success". Or maybe the reason it couldn't be resolved?

Original report: https://github.com/igrigorik/em-http-request/issues/299

**Comment by sodabrew** [comment]
Looks like the correct thing to do for getaddrinfo failures is not `strerror`, but rather `gai_strerror`: https://linux.die.net/man/3/gai_strerror http://docs.oracle.com/cd/E23823_01/html/816-5170/getaddrinfo-3socket.html
