### ISSUE TITLE
eventmachine not initialized: evma_signal_loopbreak

### ISSUE THREAD

**Issue by mattheworiordan** [eventmachine/eventmachine#756]
I am running EventMachine as part of an RSpec test suite, see https://github.com/ably/ably-ruby/blob/master/spec/support/event_machine_helper.rb for the somewhat hacky way to replace the test block with a block that runs a reactor and yields to the test block.  This is convenient because one can simply tag a test / context with `:event_machine` (such as https://github.com/ably/ably-ruby/blob/master/spec/acceptance/realtime/auth_spec.rb#L7), and it all just works.

However, I have found that I can consistently get EM into a state where it raises an exception when starting the reactor:

```
RuntimeError:
       eventmachine not initialized: evma_signal_loopbreak
     # /Users/mattheworiordan/.rvm/gems/ruby-2.2.5/gems/eventmachine-1.2.1/lib/eventmachine.rb:1133:in `signal_loopbreak'
     # /Users/mattheworiordan/.rvm/gems/ruby-2.2.5/gems/eventmachine-1.2.1/lib/eventmachine.rb:1133:in `next_tick'
     # ./lib/ably/realtime/connection/connection_manager.rb:31:in `initialize'
```

Now when I catch that exception and run a `pry` at that point, I get some odd results:

```
[1] pry(RSpec::EventMachine)> e
=> #<RuntimeError: eventmachine not initialized: evma_signal_loopbreak>
[2] pry(RSpec::EventMachine)> ::EventMachine.reactor_running?
=> true
[3] pry(RSpec::EventMachine)> ::EventMachine.stop
RuntimeError: eventmachine not initialized: evma_stop_machine
from (pry):4:in `stop'
[4] pry(RSpec::EventMachine)> ::EventMachine.stopping?
RuntimeError: eventmachine not initialized: evma_stopping
from (pry):5:in `stopping?'
[5] pry(RSpec::EventMachine)> EM.next_tick { puts "a" }
RuntimeError: eventmachine not initialized: evma_signal_loopbreak
from /Users/mattheworiordan/.rvm/gems/ruby-2.2.5/gems/eventmachine-1.2.1/lib/eventmachine.rb:1133:in `signal_loopbreak'
```

So it thinks it is running, yet it's raised a `eventmachine not initialized: evma_signal_loopbreak` exception when accessing any EM feature.  If I try and stop EM it tells me it's not running.

From this point forwards my test suite fails unilaterally as there is no way to resurrect or kill EM completely.

I have tried all sorts of permutations to get this fixed such as spawning threads, explicitly killing the reactor even though I know it's terminated at the end of each test, and nothing I do seems to help.

I am on OS X, Ruby 2.2.1 and 2.2.5, and have upgraded to the latest EM 1.2.1 as well.

Any advice on what I could do would be appreciated.

**Comment by sodabrew** [comment]
Super interesting bug! Thank you for the thorough description of the problem! I'll give the code a walk-through to see if there's some obvious failure point that can induce this.

**Comment by mattheworiordan** [comment]
@sodabrew FYI, you can see this problem in action on an open source repo that is running on Travis, see https://travis-ci.org/ably/ably-ruby/jobs/188496783

As you will see, one test fails, and then all subsequent tests fail because of the `evma_signal_loopbreak` bug breaking the test suite completely.  You can see it passing though at https://travis-ci.org/ably/ably-ruby/jobs/188496784 so it does work :/

Shout if you think I can help with reproducing the issue.

**Comment by mattheworiordan** [comment]
@sodabrew just wondering if you had any time to investigate?

**Comment by sodabrew** [comment]
I haven't yet, sorry!

**Comment by mattheworiordan** [comment]
Hey @sodabrew disappointingly we're still seeing this quite frequently.  Anything I can do to help debug perhaps?

**Comment by relonger** [comment]
Seems to got the same issue in my code. It runs a lot of EM.defer calls inside EM::Defferable class which processed and queried by EM::Pool wrapper.

**Comment by singpolyma-shopify** [comment]
I think there is a race-condition in `next_tick` where `reactor_running?` may be true *just* before it is safe to call `signal_loopbreak`

**Comment by mattheworiordan** [comment]
I continue to get this error sadly, 1.5 years on.  It would be great if we could get this resolved somehow.

**Comment by sodabrew** [comment]
Coincidentally I’ve just been able to repro this on OSX if I am using Ruby with jemalloc, and/or with an SSL initialization error. Is anybody doing a combination of those things as well?

**Comment by mattheworiordan** [comment]
Nice, thanks.  I'll wait for the release and confirm if this resolves the problem for us.

**Comment by mattheworiordan** [comment]
@sodabrew thanks, [nice green build](https://travis-ci.org/ably/ably-ruby/builds/373170069?utm_source=github_status&utm_medium=notification), let's hope the issue is resolved permanently.  Thanks for your help with this.
