### ISSUE TITLE
No IPv6 in pure ruby

### ISSUE THREAD

**Issue by lobeck** [eventmachine/eventmachine#763]
Connections to dual stack hosts fail, if pure ruby is used. This is most probably caused by `AF_INET` in https://github.com/eventmachine/eventmachine/blob/master/lib/em/pure_ruby.rb#L875

	/opt/sensu/embedded/lib/ruby/2.3.0/socket.rb:1207:in `__connect_nonblock': Address family not supported by protocol - connect(2) for [2
	a03:foo:bar::1]:5671 (Errno::EAFNOSUPPORT)
	        from /opt/sensu/embedded/lib/ruby/2.3.0/socket.rb:1207:in `connect_nonblock'
	        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.1/lib/em/pure_ruby.rb:882:in `connect'
	        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.1/lib/em/pure_ruby.rb:168:in `bind_connect_server'
	        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.1/lib/em/pure_ruby.rb:163:in `connect_server'
	        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.1/lib/eventmachine.rb:677:in `bind_connect'
	        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.1/lib/eventmachine.rb:653:in `connect'

**Comment by sodabrew** [comment]
Thanks, that looks like the problem. Scheduling this for next fix release.

**Comment by sodabrew** [comment]
Moving this to 1.3.0 because the change is a little deeper than a point release.
