### ISSUE TITLE
run_machine: unknown connection (EventMachine::ConnectionNotBound)

### ISSUE THREAD

**Issue by djensenius** [eventmachine/eventmachine#805]
I'm running into this error a lot:

```
vendor/bundle/ruby/2.3.0/gems/eventmachine-1.2.5/lib/eventmachine.rb:194:in `run_machine': unknown connection: 312 (EventMachine::ConnectionNotBound)
    from vendor/bundle/ruby/2.3.0/gems/eventmachine-1.2.5/lib/eventmachine.rb:194:in `run'
    from bin/kafka-consumer:292:in `block in <top (required)>'
```

Exception reporting shows this coming from the `EM.run` line, but rescuing that does not catch anything and the error continues to be reported.

The theory is that this occurs during shutdown (we run EM in a background thread... maybe when the main thread exits this causes an issue?) when we're restarting anyway, so it isn't affecting us a *lot* but is super annoying and would like to understand more.

**Comment by alexandrule** [comment]
I also have this issue and trying to find a solution.
@djensenius Did you find a solution?

**Comment by sodabrew** [comment]
I cannot reproduce this myself. If you can post a small script that triggers this error, I'd be glad to run it down.

**Comment by abepetrillo** [comment]
I know this is an old bug but it's still open so...
We have regularly come across this when trying to do:
```ruby
EventMachine.run do
end
```

This crashes pretty regularly on Heroku. Not sure if it matters but we call this code via sidekiq worker so:
```ruby
require 'eventmachine'

class StartEventMachineWorker
  include Sidekiq::Worker

  sidekiq_options queue: :event_machine, retry: 12, backtrace: true

  def perform
    EventMachine.run do
    end
  end
end
```
