### ISSUE TITLE
Segfault

### ISSUE THREAD

**Issue by singpolyma-shopify** [eventmachine/eventmachine#809]
```
irb> time = nil; EM.next_tick { puts Benchmark.measure { time = Time.now; EMPromise.all((1..2000).map { |x| EM::HttpRequest.new("https://www.google.com").get.promise }).then { puts (Time.now - time) } } }
=> nil
irb(main):003:0>   0.880000   1.200000   2.080000 ( 16.211140)
/app/vendor/bundle/ruby/2.4.0/gems/em-http-request-1.1.5/lib/em-http/http_connection.rb:160: [BUG] Segmentation fault at 0x00000000001155d0
ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux]

-- Control frame information -----------------------------------------------
c:0006 p:0013 s:0026 e:000025 METHOD /app/vendor/bundle/ruby/2.4.0/gems/em-http-request-1.1.5/lib/em-http/http_connection.rb:160
c:0005 p:0010 s:0022 e:000021 METHOD /app/vendor/bundle/ruby/2.4.0/gems/em-http-request-1.1.5/lib/em-http/http_connection.rb:27 [FINISH]
c:0004 p:---- s:0018 e:000017 CFUNC  :run_machine
c:0003 p:0327 s:0014 e:000013 METHOD /app/vendor/bundle/ruby/2.4.0/gems/eventmachine-1.2.5/lib/eventmachine.rb:194
c:0002 p:0014 s:0006 e:000005 BLOCK  (irb):1 [FINISH]
c:0001 p:---- s:0003 e:000002 (none) [FINISH]

-- Ruby level backtrace information ----------------------------------------
(irb):1:in `block in irb_binding'
/app/vendor/bundle/ruby/2.4.0/gems/eventmachine-1.2.5/lib/eventmachine.rb:194:in `run'
/app/vendor/bundle/ruby/2.4.0/gems/eventmachine-1.2.5/lib/eventmachine.rb:194:in `run_machine'
/app/vendor/bundle/ruby/2.4.0/gems/em-http-request-1.1.5/lib/em-http/http_connection.rb:27:in `connection_completed'
/app/vendor/bundle/ruby/2.4.0/gems/em-http-request-1.1.5/lib/em-http/http_connection.rb:160:in `connection_completed'

-- Machine register context ------------------------------------------------
 RIP: 0x00007f297e40ae21 RBP: 0x0000000000000190 RSP: 0x00007f2967de1a20
 RAX: 0x0000000000020000 RBX: 0x00007f2960000020 RCX: 0x0000000000000071
 RDX: 0x00007f2960000778 RDI: 0x00007f2960000778 RSI: 0x0000000000000090
  R8: 0x0000000000000002  R9: 0x00000000001155c0 R10: 0x0000563eb69660e0
 R11: 0x0000563eb3620ea0 R12: 0x00007f296000cec0 R13: 0x0000000000000019
 R14: 0x00007f2960000078 R15: 0x000000000000270f EFL: 0x0000000000010206

-- C level backtrace information -------------------------------------------
```

**Comment by singpolyma-shopify** [comment]
`EM.epoll` fixes it

**Comment by sodabrew** [comment]
What's an `EMPromise`?

**Comment by singpolyma-shopify** [comment]
Oh, apologies, it's a binding onto promise.rb -- the point is that attempting to open too many FDs at once for the `select` mode (when you have not called (`EM.epoll`) you get a segfault instead of any helpful error

**Comment by sodabrew** [comment]
Aha, thank you! This one? https://github.com/lgierth/promise.rb

**Comment by singpolyma-shopify** [comment]
Yes, that on. Here's a version of the glue: https://gitlab.com/ossguy/sgx-catapult/blob/master/em_promise.rb

**Comment by sodabrew** [comment]
Possibly #843 if the same select size requirements are on Linux as well.
