### ISSUE TITLE
unable to get peer name

### ISSUE THREAD

**Issue by jimu001** [eventmachine/eventmachine#821]
Hi, This error is occurring very frequently in my Thin server logs. Has anyone else been experiencing this?

Thin web server (v1.7.2 codename Bachmanity)
Maximum connections set to 1024
Listening on 127.0.0.1:3003, CTRL+C to stop
Could not infer remote address: unable to get peer name: Transport endpoint is not connected
        /usr/local/lib/ruby/gems/1.8/gems/eventmachine-1.2.5/lib/em/connection.rb:597:in `get_peername'
        /usr/local/lib/ruby/gems/1.8/gems/eventmachine-1.2.5/lib/em/connection.rb:597:in `get_peername'
        /usr/local/lib/ruby/gems/1.8/gems/thin-1.7.2/lib/thin/connection.rb:211:in `socket_address'
        /usr/local/lib/ruby/gems/1.8/gems/thin-1.7.2/lib/thin/connection.rb:202:in `remote_address'
        /usr/local/lib/ruby/gems/1.8/gems/thin-1.7.2/lib/thin/connection.rb:65:in `pre_process'
        /usr/local/lib/ruby/gems/1.8/gems/thin-1.7.2/lib/thin/connection.rb:53:in `process'
        /usr/local/lib/ruby/gems/1.8/gems/thin-1.7.2/lib/thin/connection.rb:39:in `receive_data'
        /usr/local/lib/ruby/gems/1.8/gems/eventmachine-1.2.5/lib/eventmachine.rb:194:in `run_machine'
        /usr/local/lib/ruby/gems/1.8/gems/eventmachine-1.2.5/lib/eventmachine.rb:194:in `run'
        /usr/local/lib/ruby/gems/1.8/gems/thin-1.7.2/lib/thin/backends/base.rb:73:in `start'
        /usr/local/lib/ruby/gems/1.8/gems/thin-1.7.2/lib/thin/server.rb:162:in `start'
        /usr/local/lib/ruby/gems/1.8/gems/thin-1.7.2/lib/thin/controllers/controller.rb:87:in `start'
        /usr/local/lib/ruby/gems/1.8/gems/thin-1.7.2/lib/thin/runner.rb:203:in `send'
        /usr/local/lib/ruby/gems/1.8/gems/thin-1.7.2/lib/thin/runner.rb:203:in `run_command'
        /usr/local/lib/ruby/gems/1.8/gems/thin-1.7.2/lib/thin/runner.rb:159:in `run!'
        /usr/local/lib/ruby/gems/1.8/gems/thin-1.7.2/bin/thin:6
        /usr/local/bin/thin:19:in `load'
        /usr/local/bin/thin:19

**Comment by evserykh** [comment]
@jimu001 I've met the same error using EventMachine based SMTP server. Recently I started using HAProxy and after that I started getting this error. I've never met it before using HAProxy.

**Comment by jimu001** [comment]
The errors began for me after a recent upgrade of HAProxy to latest stable version 1.8.4.

**Comment by dCSeven** [comment]
Hi, I'm having the same issue calling it in `post_init`:
```ruby
module TCPServer
  def post_init
    @port, @ip = Socket.unpack_sockaddr_in(get_peername)
    ...
  end
  ...
end
```
And here is the corresponding stacktrace:
```
 /usr/local/bundle/gems/eventmachine-1.2.5/lib/em/connection.rb:597:in `get_peername',
 /usr/local/bundle/gems/eventmachine-1.2.5/lib/em/connection.rb:597:in `get_peername',
 tcp_server.rb:61:in `post_init',
 /usr/local/bundle/gems/eventmachine-1.2.5/lib/em/connection.rb:58:in `block in new',
 /usr/local/bundle/gems/eventmachine-1.2.5/lib/em/connection.rb:49:in `instance_eval',
 /usr/local/bundle/gems/eventmachine-1.2.5/lib/em/connection.rb:49:in `new',
 /usr/local/bundle/gems/eventmachine-1.2.5/lib/eventmachine.rb:1514:in `event_callback',
 /usr/local/bundle/gems/eventmachine-1.2.5/lib/eventmachine.rb:194:in `run_machine',
 /usr/local/bundle/gems/eventmachine-1.2.5/lib/eventmachine.rb:194:in `run'
 tcp_server.rb:255:in `<main>'
```

Sadly I cannot reproduce it, but it occurs every now and then. Therefore it would be great if someone could tell why this occurs (and how to fix it).

**Comment by evserykh** [comment]
@dCSeven do you use HAProxy? I can't explain the reason but I was forced to use `rescue` like this:

```
def post_init
  _, ip = Socket.unpack_sockaddr_in(get_peername)
  close_connection_after_writing if !start_session(ip)
  logger.info "Connection from #{ip}"
rescue => e
  log_error e
end
```

**Comment by dCSeven** [comment]
Yes
The current architecture is a HAProxy on the outside (only forwards traffic)
  to Docker Swarm(which does the Load Balancing & contains the containers with my application on it)
 Do you think the Load Balancing causes this?

Yeah, the `rescue` absolutely makes sense (this is my current workaround too; forgot to include it here).

**Comment by evserykh** [comment]
@dCSeven For now we just use `rescue` and I don't know how to get rid of this.

**Comment by dCSeven** [comment]
Ok, thank you.

Therefore I'll just log them as `Warning` instead of `Error`  and hope that they don't increase.

**Comment by timon** [comment]
I'm also experiencing this, and I'm also using haproxy in front of my application.

With native extension, this is what gets recorded in systemd journal:

```syslog
Sep 26 13:09:25 insomniac bash[31249]: pure virtual method called
Sep 26 13:09:25 insomniac bash[31249]: terminate called after throwing an instance of 'std::runtime_error'
Sep 26 13:09:25 insomniac bash[31249]: what():  unable to get peer name: Transport endpoint is not connected
Sep 26 13:09:27 insomniac systemd[1]: meh.service: main process exited, code=killed, status=6/ABRT
Sep 26 13:09:27 insomniac systemd[1]: Unit meh.service entered failed state.
Sep 26 13:09:27 insomniac systemd[1]: meh.service failed.
Sep 26 13:09:27 insomniac systemd[1]: meh.service holdoff time over, scheduling restart.
Sep 26 13:09:27 insomniac systemd[1]: Started Meh server
```

Not sure if there is a place to put `rescue` in it to avoid SIGABRT

**Comment by sodabrew** [comment]
This throw should be caught already: cc0270a16afaa7b8649ebc2f7a53eaa3b348eb4c

**Comment by timon** [comment]
Hi @sodabrew, I'm running `1.2.7`, and the only reference to `get_peername` in my code is this:

```ruby
    def peer_string
      @peer_string ||= Socket.unpack_sockaddr_in(get_peername).join(":")
    rescue
      "[no peer name?]"
    end
```

I'll try to wrap the assignment into `begin-rescue-end` block, but I'm not sure if it helps

**Comment by ThomasSevestre** [comment]
I had similar errors when calling `get_peername` in `post_init`
I works reliably in `connection_completed` callback
