### ISSUE TITLE
Unable to load the EventMachine C extension

### ISSUE THREAD

**Issue by rahuldwivedi** [eventmachine/eventmachine#863]
I am using ruby-1.9.3-p551 and ubuntu 16.04
I am having issue when running ``` rails c ```

```
Unable to load the EventMachine C extension; To use the pure-ruby reactor, require 'em/pure_ruby'

```

my system logs are :

```
Unable to load the EventMachine C extension; To use the pure-ruby reactor, require 'em/pure_ruby'
/home/rails/.rvm/gems/ruby-1.9.3-p551@ie-events/gems/activesupport-3.2.22.1/lib/active_support/dependencies.rb:251:in `require': incompatible library version - /home/rails/.rvm/gems/ruby-1.9.3-p551@ie-events/gems/eventmachine-1.0.3/lib/rubyeventmachine.so (LoadError)
	from /home/rails/.rvm/gems/ruby-1.9.3-p551@ie-events/gems/activesupport-3.2.22.1/lib/active_support/dependencies.rb:251:in `block in require'
	from /home/rails/.rvm/gems/ruby-1.9.3-p551@ie-events/gems/activesupport-3.2.22.1/lib/active_support/dependencies.rb:236:in `load_dependency'
	from /home/rails/.rvm/gems/ruby-1.9.3-p551@ie-events/gems/activesupport-3.2.22.1/lib/active_support/dependencies.rb:251:in `require'
	from /home/rails/.rvm/gems/ruby-1.9.3-p551@ie-events/gems/eventmachine-1.0.3/lib/eventmachine.rb:8:in `<top (required)>'
	from /home/rails/.rvm/gems/ruby-1.9.3-p551@ie-events/gems/activesupport-3.2.22.1/lib/active_support/dependencies.rb:251:in `require'
	from /home/rails/.rvm/gems/ruby-1.9.3-p551@ie-events/gems/activesupport-3.2.22.1/lib/active_support/dependencies.rb:251:in `block in require'
	from /home/rails/.rvm/gems/ruby-1.9.3-p551@ie-events/gems/activesupport-3.2.22.1/lib/active_support/dependencies.rb:236:in `load_dependency'
	from /home/rails/.rvm/gems/ruby-1.9.3-p551@ie-events/gems/activesupport-3.2.22.1/lib/active_support/dependencies.rb:251:in `require'
	from /home/rails/.rvm/gems/ruby-1.9.3-p551@ie-events/gems/faye-websocket-0.4.7/lib/faye/websocket.rb:17:in `<top (required)>'
	from /home/rails/.rvm/gems/ruby-1.9.3-p551@ie-events/gems/activesupport-3.2.22.1/lib/active_support/dependencies.rb:251:in `require'
	from /home/rails/.rvm/gems/ruby-1.9.3-p551@ie-events/gems/activesupport-3.2.22.1/lib/active_support/dependencies.rb:251:in `block in require'
	from /home/rails/.rvm/gems/ruby-1.9.3-p551@ie-events/gems/activesupport-3.2.22.1/lib/active_support/dependencies.rb:236:in `load_dependency'
	from /home/rails/.rvm/gems/ruby-1.9.3-p551@ie-events/gems/activesupport-3.2.22.1/lib/active_support/dependencies.rb:251:in `require'
	from /home/rails/.rvm/gems/ruby-1.9.3-p551@ie-events/bundler/gems/poltergeist-7dee7758a03d/lib/capybara/poltergeist/web_socket_server.rb:4:in `<top (required)>'
	from /home/rails/.rvm/gems/ruby-1.9.3-p551@ie-events/gems/activesupport-3.2.22.1/lib/active_support/dependencies.rb:251:in `require'
	from /home/rails/.rvm/gems/ruby-1.9.3-p551@ie-events/gems/activesupport-3.2.22.1/lib/active_support/dependencies.rb:251:in `block in require'
	from /home/rails/.rvm/gems/ruby-1.9.3-p551@ie-events/gems/activesupport-3.2.22.1/lib/active_support/dependencies.rb:236:in `load_dependency'
	from /home/rails/.rvm/gems/ruby-1.9.3-p551@ie-events/gems/activesupport-3.2.22.1/lib/active_support/dependencies.rb:251:in `require'
	from /home/rails/.rvm/gems/ruby-1.9.3-p551@ie-events/bundler/gems/poltergeist-7dee7758a03d/lib/capybara/poltergeist.rb:15:in `<module:Poltergeist>'
	from /home/rails/.rvm/gems/ruby-1.9.3-p551@ie-events/bundler/gems/poltergeist-7dee7758a03d/lib/capybara/poltergeist.rb:9:in `<module:Capybara>'
	from /home/rails/.rvm/gems/ruby-1.9.3-p551@ie-events/bundler/gems/poltergeist-7dee7758a03d/lib/capybara/poltergeist.rb:8:in `<top (required)>'
	from /home/rails/.rvm/gems/ruby-1.9.3-p551@ie-events/gems/activesupport-3.2.22.1/lib/active_support/dependencies.rb:251:in `require'
	from /home/rails/.rvm/gems/ruby-1.9.3-p551@ie-events/gems/activesupport-3.2.22.1/lib/active_support/dependencies.rb:251:in `block in require'
	from /home/rails/.rvm/gems/ruby-1.9.3-p551@ie-events/gems/activesupport-3.2.22.1/lib/active_support/dependencies.rb:236:in `load_dependency'
	from /home/rails/.rvm/gems/ruby-1.9.3-p551@ie-events/gems/activesupport-3.2.22.1/lib/active_support/dependencies.rb:251:in `require'
	from /home/rails/rails_work/ie-events/config/initializers/konacha.rb:2:in `block in <top (required)>'
	from /home/rails/.rvm/gems/ruby-1.9.3-p551@ie-events/bundler/gems/konacha-919679732d9b/lib/konacha.rb:29:in `configure'
	from /home/rails/rails_work/ie-events/config/initializers/konacha.rb:1:in `<top (required)>'
	from /home/rails/.rvm/gems/ruby-1.9.3-p551@ie-events/gems/activesupport-3.2.22.1/lib/active_support/dependencies.rb:245:in `load'
	from /home/rails/.rvm/gems/ruby-1.9.3-p551@ie-events/gems/activesupport-3.2.22.1/lib/active_support/dependencies.rb:245:in `block in load'
	from /home/rails/.rvm/gems/ruby-1.9.3-p551@ie-events/gems/activesupport-3.2.22.1/lib/active_support/dependencies.rb:236:in `load_dependency'
	from /home/rails/.rvm/gems/ruby-1.9.3-p551@ie-events/gems/activesupport-3.2.22.1/lib/active_support/dependencies.rb:245:in `load'
	from /home/rails/.rvm/gems/ruby-1.9.3-p551@ie-events/gems/railties-3.2.22.1/lib/rails/engine.rb:593:in `block (2 levels) in <class:Engine>'
	from /home/rails/.rvm/gems/ruby-1.9.3-p551@ie-events/gems/railties-3.2.22.1/lib/rails/engine.rb:592:in `each'
	from /home/rails/.rvm/gems/ruby-1.9.3-p551@ie-events/gems/railties-3.2.22.1/lib/rails/engine.rb:592:in `block in <class:Engine>'
	from /home/rails/.rvm/gems/ruby-1.9.3-p551@ie-events/gems/railties-3.2.22.1/lib/rails/initializable.rb:30:in `instance_exec'
	from /home/rails/.rvm/gems/ruby-1.9.3-p551@ie-events/gems/railties-3.2.22.1/lib/rails/initializable.rb:30:in `run'
	from /home/rails/.rvm/gems/ruby-1.9.3-p551@ie-events/gems/railties-3.2.22.1/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /home/rails/.rvm/gems/ruby-1.9.3-p551@ie-events/gems/railties-3.2.22.1/lib/rails/initializable.rb:54:in `each'
	from /home/rails/.rvm/gems/ruby-1.9.3-p551@ie-events/gems/railties-3.2.22.1/lib/rails/initializable.rb:54:in `run_initializers'
	from /home/rails/.rvm/gems/ruby-1.9.3-p551@ie-events/gems/railties-3.2.22.1/lib/rails/application.rb:136:in `initialize!'
	from /home/rails/.rvm/gems/ruby-1.9.3-p551@ie-events/gems/railties-3.2.22.1/lib/rails/railtie/configurable.rb:30:in `method_missing'
	from /home/rails/rails_work/ie-events/config/environment.rb:5:in `<top (required)>'
	from /home/rails/.rvm/gems/ruby-1.9.3-p551@ie-events/gems/activesupport-3.2.22.1/lib/active_support/dependencies.rb:251:in `require'
	from /home/rails/.rvm/gems/ruby-1.9.3-p551@ie-events/gems/activesupport-3.2.22.1/lib/active_support/dependencies.rb:251:in `block in require'
	from /home/rails/.rvm/gems/ruby-1.9.3-p551@ie-events/gems/activesupport-3.2.22.1/lib/active_support/dependencies.rb:236:in `load_dependency'
	from /home/rails/.rvm/gems/ruby-1.9.3-p551@ie-events/gems/activesupport-3.2.22.1/lib/active_support/dependencies.rb:251:in `require'
	from /home/rails/.rvm/gems/ruby-1.9.3-p551@ie-events/gems/railties-3.2.22.1/lib/rails/application.rb:103:in `require_environment!'
	from /home/rails/.rvm/gems/ruby-1.9.3-p551@ie-events/gems/railties-3.2.22.1/lib/rails/commands.rb:40:in `<top (required)>'
	from script/rails:6:in `require'
	from script/rails:6:in `<main>'
```

**Gemfile.lock**

```

GIT
  remote: https://github.com/billmag/konacha
  revision: 919679732d9b4fc87da03c72a89aea822d03298c
  specs:
    konacha (2.1.0)
      actionpack (>= 3.1, < 5)
      capybara (~> 2.0)
      colorize
      railties (>= 3.1, < 5)
      sprockets

GIT
  remote: https://github.com/jonleighton/poltergeist
  revision: 7dee7758a03d4636c2a74b04a8b7bf8495319217
  specs:
    poltergeist (1.3.0)
      capybara (~> 2.1.0)
      faye-websocket (>= 0.4.4, < 0.5.0)
      http_parser.rb (~> 0.5.3)

GEM
  remote: https://rubygems.org/
  specs:
    actionmailer (3.2.22.1)
      actionpack (= 3.2.22.1)
      mail (~> 2.5.4)
    actionpack (3.2.22.1)
      activemodel (= 3.2.22.1)
      activesupport (= 3.2.22.1)
      builder (~> 3.0.0)
      erubis (~> 2.7.0)
      journey (~> 1.0.4)
      rack (~> 1.4.5)
      rack-cache (~> 1.2)
      rack-test (~> 0.6.1)
      sprockets (~> 2.2.1)
    active_record_query_trace (1.5.2)
    activemodel (3.2.22.1)
      activesupport (= 3.2.22.1)
      builder (~> 3.0.0)
    activerecord (3.2.22.1)
      activemodel (= 3.2.22.1)
      activesupport (= 3.2.22.1)
      arel (~> 3.0.2)
      tzinfo (~> 0.3.29)
    activeresource (3.2.22.1)
      activemodel (= 3.2.22.1)
      activesupport (= 3.2.22.1)
    activesupport (3.2.22.1)
      i18n (~> 0.6, >= 0.6.4)
      multi_json (~> 1.0)
    acts_as_singleton (0.0.8)
      activerecord (>= 3.1.0)
    addressable (2.3.8)
    airbrake (5.6.1)
      airbrake-ruby (~> 1.6)
    airbrake-ruby (1.6.0)
    arel (3.0.3)
    ast (2.2.0)
    atomic (1.1.9)
    bcrypt-ruby (3.0.1)
    better_errors (0.8.0)
      coderay (>= 1.0.0)
      erubis (>= 2.6.6)
    binding_of_caller (0.7.2)
      debug_inspector (>= 0.0.1)
    bootstrap-sass-rails (2.2.2.0)
      railties (>= 3.1.0)
      sass-rails (>= 3.1.0)
    bourbon (3.0.1)
      sass (>= 3.2.0)
      thor
    brakeman (3.1.2)
      erubis (~> 2.6)
      fastercsv (~> 1.5)
      haml (>= 3.0, < 5.0)
      highline (~> 1.6)
      multi_json (~> 1.2)
      ruby2ruby (>= 2.1.1, < 2.3.0)
      ruby_parser (~> 3.7.0)
      safe_yaml
      sass (~> 3.0)
      slim (>= 1.3.6, < 4.0)
      terminal-table (~> 1.4)
    browser (0.9.1)
    builder (3.0.4)
    bullet (4.3.0)
      uniform_notifier
    cache_digests (0.3.0)
      actionpack (>= 3.2)
      thread_safe
    capistrano (2.15.4)
      highline
      net-scp (>= 1.0.0)
      net-sftp (>= 2.0.0)
      net-ssh (>= 2.0.14)
      net-ssh-gateway (>= 1.1.0)
    capistrano-db-tasks (0.2.1)
    capistrano_colors (0.5.5)
    capybara (2.1.0)
      mime-types (>= 1.16)
      nokogiri (>= 1.3.3)
      rack (>= 1.0.0)
      rack-test (>= 0.5.4)
      xpath (~> 2.0)
    capybara-screenshot (1.0.11)
      capybara (>= 1.0, < 3)
      launchy
    capybara-webkit (1.3.1)
      capybara (>= 2.0.2, < 2.5.0)
      json
    chronic (0.10.2)
    climate_control (0.0.3)
      activesupport (>= 3.0)
    cocaine (0.5.3)
      climate_control (>= 0.0.3, < 1.0)
    coderay (1.1.0)
    coffee-rails (3.2.2)
      coffee-script (>= 2.2.0)
      railties (~> 3.2.0)
    coffee-script (2.2.0)
      coffee-script-source
      execjs
    coffee-script-source (1.6.2)
    colorize (0.5.8)
    combine_pdf (0.2.16)
      ruby-rc4 (>= 0.1.5)
    daemons (1.1.9)
    database_cleaner (1.0.1)
    debug_inspector (0.0.2)
    devise (2.2.4)
      bcrypt-ruby (~> 3.0)
      orm_adapter (~> 0.1)
      railties (~> 3.1)
      warden (~> 1.2.1)
    diff-lcs (1.2.5)
    dotenv (0.7.0)
    dragonfly (1.0.12)
      addressable (~> 2.3)
      multi_json (~> 1.0)
      rack (>= 1.3.0)
    dragonfly-s3_data_store (1.0.5)
      dragonfly (~> 1.0)
      fog
    draper (0.18.0)
      actionpack (~> 3.2)
      activesupport (~> 3.2)
    erubis (2.7.0)
    eventmachine (1.0.3)
    excon (0.22.1)
    execjs (1.4.0)
      multi_json (~> 1.0)
    factory_girl (4.5.0)
      activesupport (>= 3.0.0)
    factory_girl_rails (4.5.0)
      factory_girl (~> 4.5.0)
      railties (>= 3.0.0)
    faraday (0.8.7)
      multipart-post (~> 1.1)
    faraday_middleware (0.10.0)
      faraday (>= 0.7.4, < 0.10)
    fastercsv (1.5.5)
    faye-websocket (0.4.7)
      eventmachine (>= 0.12.0)
    ffaker (2.1.0)
    fog (1.11.1)
      builder
      excon (~> 0.20)
      formatador (~> 0.2.0)
      json (~> 1.7)
      mime-types
      net-scp (~> 1.1)
      net-ssh (>= 2.1.3)
      nokogiri (~> 1.5.0)
      ruby-hmac
    formatador (0.2.4)
    get_process_mem (0.2.0)
    haml (4.0.7)
      tilt
    has_scope (0.5.1)
    hashie (2.0.5)
    highline (1.6.19)
    hike (1.2.3)
    http_parser.rb (0.5.3)
    httparty (0.13.7)
      json (~> 1.8)
      multi_xml (>= 0.5.2)
    i18n (0.7.0)
    inherited_resources (1.4.0)
      has_scope (~> 0.5.0)
      responders (~> 0.9)
    intercom-rails (0.2.28)
      activesupport (> 3.0)
    jbuilder (1.4.1)
      activesupport (>= 3.0.0)
      multi_json (>= 1.2.0)
    journey (1.0.4)
    jquery-rails (2.1.4)
      railties (>= 3.0, < 5.0)
      thor (>= 0.14, < 2.0)
    json (1.8.3)
    launchy (2.4.3)
      addressable (~> 2.3)
    letter_opener (1.4.1)
      launchy (~> 2.2)
    libv8 (3.16.14.11)
    mail (2.5.4)
      mime-types (~> 1.16)
      treetop (~> 1.4.8)
    method_source (0.8.2)
    mime-types (1.25.1)
    multi_json (1.11.2)
    multi_xml (0.5.5)
    multipart-post (1.2.0)
    mysql2 (0.3.17)
    neat (1.0.2)
      bourbon (>= 2.1)
      sass (>= 3.2)
    net-scp (1.1.1)
      net-ssh (>= 2.6.5)
    net-sftp (2.1.2)
      net-ssh (>= 2.6.5)
    net-ssh (2.6.7)
    net-ssh-gateway (1.2.0)
      net-ssh (>= 2.6.5)
    newrelic_rpm (3.15.0.314)
    nokogiri (1.5.9)
    omniauth (1.1.4)
      hashie (>= 1.2, < 3)
      rack
    orm_adapter (0.4.0)
    paper_trail (2.7.1)
      activerecord (~> 3.0)
      railties (~> 3.0)
    paperclip (3.4.2)
      activemodel (>= 3.0.0)
      activerecord (>= 3.0.0)
      activesupport (>= 3.0.0)
      cocaine (~> 0.5.0)
      mime-types
    parser (2.3.0.6)
      ast (~> 2.2)
    pdf-core (0.4.0)
    polyglot (0.3.5)
    powerpack (0.1.1)
    prawn (1.3.0)
      pdf-core (~> 0.4.0)
      ttfunk (~> 1.4.0)
    pry (0.10.3)
      coderay (~> 1.1.0)
      method_source (~> 0.8.1)
      slop (~> 3.4)
    pry-rails (0.3.4)
      pry (>= 0.9.10)
    puma (2.15.3)
    puma_worker_killer (0.0.4)
      get_process_mem (~> 0.2)
      puma (~> 2.7)
    quiet_assets (1.0.2)
      railties (>= 3.1, < 5.0)
    rack (1.4.7)
    rack-cache (1.6.1)
      rack (>= 0.4)
    rack-ssl (1.3.4)
      rack
    rack-test (0.6.3)
      rack (>= 1.0)
    rails (3.2.22.1)
      actionmailer (= 3.2.22.1)
      actionpack (= 3.2.22.1)
      activerecord (= 3.2.22.1)
      activeresource (= 3.2.22.1)
      activesupport (= 3.2.22.1)
      bundler (~> 1.0)
      railties (= 3.2.22.1)
    railties (3.2.22.1)
      actionpack (= 3.2.22.1)
      activesupport (= 3.2.22.1)
      rack-ssl (~> 1.3.2)
      rake (>= 0.8.7)
      rdoc (~> 3.4)
      thor (>= 0.14.6, < 2.0)
    rainbow (2.1.0)
    rake (11.1.2)
    rdoc (3.12.2)
      json (~> 1.4)
    ref (2.0.0)
    requirejs-rails (0.9.1)
      railties (>= 3.1.1, < 3.3)
    responders (0.9.3)
      railties (~> 3.1)
    rest-client (1.6.7)
      mime-types (>= 1.16)
    restforce (1.4.3)
      faraday (~> 0.8.4)
      faraday_middleware (>= 0.8.8)
      hashie (>= 1.2.0, < 2.1)
      json (>= 1.7.5, < 1.9.0)
    rspec (2.13.0)
      rspec-core (~> 2.13.0)
      rspec-expectations (~> 2.13.0)
      rspec-mocks (~> 2.13.0)
    rspec-core (2.13.1)
    rspec-expectations (2.13.0)
      diff-lcs (>= 1.1.3, < 2.0)
    rspec-mocks (2.13.1)
    rspec-rails (2.13.2)
      actionpack (>= 3.0)
      activesupport (>= 3.0)
      railties (>= 3.0)
      rspec-core (~> 2.13.0)
      rspec-expectations (~> 2.13.0)
      rspec-mocks (~> 2.13.0)
    rubocop (0.37.2)
      parser (>= 2.3.0.4, < 3.0)
      powerpack (~> 0.1)
      rainbow (>= 1.99.1, < 3.0)
      ruby-progressbar (~> 1.7)
      unicode-display_width (~> 0.3)
    rubocop-rspec (1.4.0)
    ruby-hmac (0.4.0)
    ruby-progressbar (1.7.5)
    ruby-rc4 (0.1.5)
    ruby2ruby (2.2.0)
      ruby_parser (~> 3.1)
      sexp_processor (~> 4.0)
    ruby_parser (3.7.2)
      sexp_processor (~> 4.1)
    safe_yaml (1.0.4)
    sanitize (2.0.3)
      nokogiri (>= 1.4.4, < 1.6)
    sass (3.4.22)
    sass-rails (3.2.6)
      railties (~> 3.2.0)
      sass (>= 3.1.10)
      tilt (~> 1.3)
    seedbank (0.3.0)
    select2-rails (3.2.1)
      thor (~> 0.14)
    sexp_processor (4.6.0)
    simple_form (2.1.0)
      actionpack (~> 3.0)
      activemodel (~> 3.0)
    sitemap_generator (5.1.0)
      builder
    slim (3.0.6)
      temple (~> 0.7.3)
      tilt (>= 1.3.3, < 2.1)
    slop (3.6.0)
    sprockets (2.2.3)
      hike (~> 1.2)
      multi_json (~> 1.0)
      rack (~> 1.0)
      tilt (~> 1.1, != 1.3.0)
    stripe (1.8.3)
      multi_json (>= 1.0.4, < 2)
      rest-client (~> 1.4)
    temple (0.7.6)
    terminal-table (1.5.2)
    therubyracer (0.12.2)
      libv8 (~> 3.16.14.0)
      ref
    thor (0.19.1)
    thread_safe (0.1.0)
      atomic
    tilt (1.4.1)
    treetop (1.4.15)
      polyglot
      polyglot (>= 0.3.1)
    ttfunk (1.4.0)
    tzinfo (0.3.46)
    uglifier (1.3.0)
      execjs (>= 0.3.0)
      multi_json (~> 1.0, >= 1.0.2)
    unicode-display_width (0.3.1)
    uniform_notifier (1.2.0)
    vmstat (2.1.0)
    warden (1.2.1)
      rack (>= 1.0)
    whenever (0.9.4)
      chronic (>= 0.6.3)
    wicked_pdf (0.9.6)
      rails
    wkhtmltopdf-binary (0.9.9.1)
    xpath (2.0.0)
      nokogiri (~> 1.3)

PLATFORMS
  ruby

DEPENDENCIES
  active_record_query_trace
  acts_as_singleton
  airbrake (= 5.6.1)
  airbrake-ruby (= 1.6.0)
  better_errors
  binding_of_caller
  bootstrap-sass-rails (= 2.2.2.0)
  bourbon (= 3.0.1)
  brakeman
  browser
  bullet (= 4.3.0)
  cache_digests
  capistrano
  capistrano-db-tasks
  capistrano_colors
  capybara
  capybara-screenshot
  capybara-webkit
  coffee-rails (= 3.2.2)
  combine_pdf
  daemons
  database_cleaner
  devise
  dotenv
  dragonfly
  dragonfly-s3_data_store
  draper (= 0.18.0)
  factory_girl_rails
  faraday
  ffaker
  fog
  httparty
  inherited_resources
  intercom-rails
  jbuilder
  jquery-rails (= 2.1.4)
  konacha!
  letter_opener
  mysql2 (= 0.3.17)
  neat (= 1.0.2)
  newrelic_rpm (= 3.15.0.314)
  omniauth
  paper_trail
  paperclip (= 3.4.2)
  poltergeist!
  prawn (= 1.3.0)
  pry
  pry-rails
  puma
  puma_worker_killer
  quiet_assets
  rack-cache
  rails (= 3.2.22.1)
  requirejs-rails
  restforce
  rspec
  rspec-rails
  rubocop
  rubocop-rspec
  sanitize (= 2.0.3)
  sass-rails (= 3.2.6)
  seedbank
  select2-rails (= 3.2.1)
  simple_form
  sitemap_generator
  stripe
  therubyracer
  uglifier (= 1.3.0)
  vmstat
  whenever
  wicked_pdf
  wkhtmltopdf-binary

BUNDLED WITH
   1.17.1

```

**Comment by sodabrew** [comment]
Some googling on your error suggests that:
> The `incompatible library version` error means that the version of Ruby the extension was linked against is not the same one that it's being loaded with.

So this error should not be relevant to the version of EventMachine you're using, but 1.0.3 is super old, and Ruby 1.9.3 is super old, so honestly I don't remember many of the details of the bugs or gotchas from 4-5 years ago.

I strongly advise upgrading your EventMachine - all the way to latest EM 1.2.x still supports Ruby 1.9.3 if you're stuck for other reasons.

**Comment by sodabrew** [comment]
Closing due to lack of updates.
