### ISSUE TITLE
jekyll --livereload gives bad file descriptor error in Windows

### ISSUE THREAD

**Issue by SteveALee** [eventmachine/eventmachine#869]
Did a Windows cmd install of Jeckyll but getting this error after a few seconds. 

Is OK without ```--livereload```
The ```$ gem install eventmachine --platform ruby``` in #806 makes no difference

```bash
$ bundle exec jekyll serve --livereload
Configuration file: C:/projects/wai-coga/_config.yml
            Source: C:/projects/wai-coga
       Destination: C:/projects/wai-coga/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
      Remote Theme: Using theme w3c/wai-website-theme
                    done in 3.788 seconds.
  Please add the following to your Gemfile to avoid polling for changes:
    gem 'wdm', '>= 0.1.0' if Gem.win_platform?
 Auto-regeneration: enabled for 'C:/projects/wai-coga'
# assume 'em/pure_ruby' was loaded already
LiveReload address: http://127.0.0.1:35729
    Server address: http://127.0.0.1:4000/wai-coga/
  Server running... press ctrl-c to stop.
#<Thread:0x000000000662da58@C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-3.7.4/lib/jekyll/commands/serve/live_reload_reactor.rb:42 run> terminated with exception (report_on_exception is true):
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/eventmachine-1.2.7/lib/em/pure_ruby.rb:559:in `close': Bad file descriptor (Errno::EBADF)
        from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/eventmachine-1.2.7/lib/em/pure_ruby.rb:559:in `block in run'
        from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/eventmachine-1.2.7/lib/em/pure_ruby.rb:559:in `each'
        from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/eventmachine-1.2.7/lib/em/pure_ruby.rb:559:in `ensure in run'
        from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/eventmachine-1.2.7/lib/em/pure_ruby.rb:562:in `run'
        from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/eventmachine-1.2.7/lib/em/pure_ruby.rb:144:in `run_machine'
        from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:198:in `run'
        from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-3.7.4/lib/jekyll/commands/serve/live_reload_reactor.rb:45:in `block in start'
jekyll 3.7.4 | Error:  Bad file descriptor

```

**Comment by SteveALee** [comment]
I assume the note about udating gemfile can be ignored as --livereload is specifically to poll for 'file' changes. Message not clear.

**Comment by SteveALee** [comment]
So when I update the gemfile the error only happens when I change the file. Which makes sense if it stops file polling but file update notifications are still getting handled.

So how to fix the bad file descriptor?

**Comment by SteveALee** [comment]
Possibly useful extra info when I run in cmd rather than Git4Windows bash

```
Error: No such file or directory @ rb_file_s_stat - C:/Users/steve/AppData/Local/Temp/jekyll-remote-theme-20190117-9880-e76rp5/assets/ableplayer/.gitattributes
             Error: Run jekyll build --trace for more information.
```

Thought that doesn't make sense to me

**Comment by sodabrew** [comment]
You're using the pure ruby runtime, which is not as well tested as it should be. Try installing again without `--platform ruby` -- the 1.2.7 release should have binaries for Windows for Ruby 2.5 included, as I recall.

**Comment by MSP-Greg** [comment]
Hate to be the bearer of bad news, but the 1.2.7 pre-compiled gem is for 2.0 <= Ruby version <= 2.3.

@SteveALee

To use a compiled version of EventMachine with Ruby 2.5, you either need:

A) The Ruby 2.5 equivalent of DevKit (MSYS2/MinGW) installed, which will allow you to compile the eventmachine gem.

B) Access to a current pre-compiled gem that you could download and install with the `-l` gem install option.

I may be able to help with either.

Finally, Windows lacks `fork` and unix sockets.  That may affect some apps that use EM...

**Comment by sodabrew** [comment]
Oh that's right. RubyInstaller2 was waaay behind at the time. Clearly a new EM release will be helpful. Thanks!

**Comment by MSP-Greg** [comment]
> RubyInstaller2 was waaay behind at the time

Just FYI, the people behind RubyInstaller didn't get much help, and it slowly faded away.  It was also developed with MSYS (which did the same), and used a proprietary system for packages, etc.

RubyInstaller2 was essentially created by one person, but it makes use of all the functionality in MSYS2, which is well supported.  For instance, 'Git for Windows' is built with it.  Also, OpenSSL 1.1.1a is the current OpenSSL package in MSYS2, and it's used for Ruby >= 2.5.

And yes, RubyInstaller2 releases are timely.

Finally, Ruby Core started fully testing 64 bit MinGW builds in Sept-2018.

> didn't realize they'd even have Ruby 2.6 posted already

Yes.  It's been used in the Appveyor code since release.  The code also includes 2.7 for the gem, with caveats re API/ABI changes...

**Comment by SteveALee** [comment]
Thanks for the comments. I'm not sure what the status is and if I can do anything?

I've tried so many things I gotton a bit lost. I'll try a clean install without ```--platform ruby``` or updating the GEM to use pure ruby.

Should I look at RubyInstaller2? The official jekyll Windows instruction mention RubyInstaller.

Sad to hear Msys has faded. I used it years ago and still use the version of MSYS Bash provided with Git 4 Windows. When Installed RubyInstaller it seemed more like a cygwin install than msys - loads and loads of packages. Pehraps I shoudl switch to WSL but I find it very slow and some things still don't work across win / WSL boundaries (eg links/junctions)

**Comment by SteveALee** [comment]
@MSP-Greg MSP Thanks for the offer of help. I installed the full dev kit - but have not build anyhting with it yes. Not sure how.

> Finally, Windows lacks fork and unix sockets. That may affect some apps that use EM...

yeah - many moons ago I did much Unix + X Windows  / Windows cross platform tools dev. It was possible to get close enough to fork with CreateProcess but winsocks sucked big time. It's a shame to hear things have not progressed in all that time :(

**Comment by MSP-Greg** [comment]
> I installed the full dev kit - but have not build anything with it yes. Not sure how.

For installing extension gems (EventMachine, Puma, etc), there is nothing to do, it should 'just work'.

I'm not sure if the OpenSSL package is included with DevKit.  If the following shows something like
`OpenSSL 1.1.1a  20 Nov 2018`, the package is installed (assuming a properly installed DevKit).

```
ruby -rdevkit -e "puts %x[openssl version]"
```

Otherwise, the following will install it:
```
ridk exec pacman -Sy openssl
```

Note that Ruby 2.4 uses OpenSSL 1.0.2{x}, Ruby 2.5 and higher uses OpenSSL 1.1.1{x}.

Finally, `ruby -reventmachine -e "puts EM.library_type, EM.ssl?"` should report the following for a properly build gem with OpenSSL support:
```
extension
true
```

**Comment by SteveALee** [comment]
@MSP-Greg 

> ruby -rdevkit -e "puts %x[openssl version]"
OpenSSL 1.1.1a  20 Nov 2018

> ruby -reventmachine -e "puts EM.library_type, EM.ssl?"
Unable to load the EventMachine C extension; To use the pure-ruby reactor, require 'em/pure_ruby'
....
1: from C:/Ruby25-x64/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
C:/Ruby25-x64/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- 2.5/rubyeventmachine (LoadError)

Which is what I did before - but the comment above says pureRuby is not good.

So I guess I need to force a build of a native 2.5/rem ?

**Comment by SteveALee** [comment]
Not clean installed the recommended
Ruby+Devkit 2.5.3-1 (x64) 
even though 
Ruby+Devkit 2.6.0-1 (x64)
is available
Then I just installed Jeckyll and bundler

**Comment by sodabrew** [comment]
Can you post the output from the gem build / install process? I'd like to see where it's failing.

**Comment by SteveALee** [comment]
The error seems to be 
```
Error: No such file or directory @ rb_sysopen - C:/Users/steve/AppData/Local/Temp/jekyll-remote-theme-20190118-5640-1uon9nb/assets/ableplayer/scripts/slider.js
             Error: Run jekyll build --trace for more information.
```
as it's looking in the TEMP folder when jekyll-remote-theme is installed elsewhere

```
$ bundle info jekyll-remote-theme
  * jekyll-remote-theme (0.3.1)
        Summary: Jekyll plugin for building Jekyll sites with any GitHub-hosted theme
        Homepage: https://github.com/benbalter/jekyll-remote-theme
        Path: C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-remote-theme-0.3.1
```

**Comment by MSP-Greg** [comment]
@SteveALee

JFYI, I believe Git for Windows is now using MSYS2.

You do seem to have everything so `gem install eventmachine --platform=ruby` should work?

**Comment by SteveALee** [comment]
@sodabrew 

Can you give me a pointer how to get that to happen again - sorry I do noe know ruby / Jekyll at all. 

Which gem are you interested in? My project one? how do I clean all the gems to forcd rebuild?

**Comment by SteveALee** [comment]
@MSP-Greg 
```
gem install eventmachine --platform=ruby
ERROR:  While executing gem ... (Gem::UnsatisfiableDependencyError)
    Unable to resolve dependency: No match for 'psych (= 3.1.0)' on this platform. Found: x64-mingw32
```

**Comment by MSP-Greg** [comment]
@SteveALee

You may have other issues.  Try:

```
 gem install eventmachine --platform=ruby --force
```

msys-1.0.dll = MSYS.  msys-2.0.dll = MSYS2.

RubyInstaller = MSYS = Ruby 2.3 and earlier
RubyInstaller2 = MSYS2 = Ruby 2.4 and later

**Comment by SteveALee** [comment]
@MSP-Greg 
The ```--force``` made no difference

So if I understand that, as I installed RubyInstaller 2.5 that is RubyInstaller2 rather than RubyInstaller2 being a completely separate project (ie fork)?

**Comment by SteveALee** [comment]
wondering if I should try ruby 2.3?

**Comment by MSP-Greg** [comment]
Not quite sure what you're asking.

RubyInstaller2 is the successor to RubyInstaller.  Ruby builds/binaries from both are available at https://rubyinstaller.org/.  The code base for the two is totally different.

As far as I know, no publicly available ruby builds have been done with RubyInstaller since 2016-Dec.

> wondering if I should try ruby 2.3?

Something is amiss.  I might suggest starting with a clean Ruby 2.5 or 2.6 install, getting Eventmachine to install, then proceed to Jekyll...

**Comment by SteveALee** [comment]
I don;t know either
I downloded ruby 2.5 from https://rubyinstaller.org/downloads/

There is no mention of RubyInstaller2 anywhere. As it was mention above I assume it was another project. Obviously just some intenral detail that confused me and I shouldl probably just ignore it?

I just did a clean install on another PC and got the same error with -live reload.

It seems I have to use the pureruby version of em but that is stating temp fiels which no longer exist.

I'm stuck and spent way to much time on this so will just not use --livereload. Hopefull it will get fixed in future.

Thanks for your help anyway :)

**Comment by MSP-Greg** [comment]
@SteveALee

JFYI, I did get Jekyll running on Windows (`bundle exec jekyll serve --livereload`) with Ruby 2.6.0.

It did take some wrestling with Bundler, I had to build a gem from a git repo, etc.  It ran fine from a PowerShell window.

It wasn't Jekyll, but some of the dependencies were messy...

**Comment by SteveALee** [comment]
I won't ask for details :) but I do hope the fixes work their way into a release ASAP. 

I'm happy if someone closes this issue. I'm not sure if the problem lies with this gem or not.

**Comment by MSP-Greg** [comment]
> I might give 2.6 a spin if it's stable enough. Despite being pushed to use 2.5 on the downloads page.

Skipping the details, 2.6 is the first Ruby version that is fully tested on Windows...

**Comment by ashmaroli** [comment]
@SteveALee Hello :wave:
I'm part of the Windows team at Jekyll and I contribute to its development using a Windows system with:
```
ruby 2.4.4p296 (2018-03-28 revision 63013) [x64-mingw32]
```
Moreover, Jekyll has its test-suite wired to AppVeyor CI to screen issues with Windows

The reason Jekyll Documentation mentions only RubyInstaller instead of specifying RubyInstaller 2 is because https://rubyinstaller.org/ doesn't show that distinction.
The difference is just under the hood. End-users need not have to concern themselves with the finer technical details because the code base is RubyInstaller till Ruby 2.3.x and RubyInstaller2 for 2.4 and above.

Feel free to open an issue ticket at [the Jekyll repository](https://github.com/jekyll/jekyll) if you find bugs. For questions regarding using Jekyll, register at our forum at https://talk.jekyllrb.com/

You may also want to go through issues filed at the [jekyll-remote-theme repo](https://github.com/benbalter/jekyll-remote-theme) to see if other users have faced similar experience as to yours.

**Comment by ashmaroli** [comment]
@MSP-Greg I tested locally with the pre-release gem artifact and it works as expected at my end
(Ruby 2.4).
Well done with pre-compiling for versions upto `Ruby 2.7` :+1:

**Comment by MSP-Greg** [comment]
Thanks for looking at it.  It actually will run with 2.7, so it's usable with trunk, but as you know, the ABI could change.  I saw some comments about 'no SSL on Windows', so feel free to add tests, etc.

JFYI, I added 'cucumber' and 'default-site', and they sort of passed.  Results here - https://ci.appveyor.com/project/MSP-Greg/jekyll/builds/21786059

Ruby 2.6.0 has an issue running gem bin files from a bash shell.  Looking into it...

**Comment by ashmaroli** [comment]
Jekyll Team would prefer to wait for an official `eventmachine-1.3.0.rc` release to pull in from Rubygems instead of the workaround. :wink:

**Comment by MSP-Greg** [comment]
I was just referring to "I tested locally with the pre-release gem artifact".

As to the repo, it obviously isn't helpful to test with what your users can't get...

**Comment by ashmaroli** [comment]
I know. I was indirectly nudging the `eventmachine` maintainers to ship a Release Candidate a.s.a.p :smiley:

**Comment by OverLordGoldDragon** [comment]
Same problem, with and without `--platform ruby`. It reloads fine once or twice then errors as below. Has this been worked around yet?

Win 10 x64, Ruby 2.7, gem 3.1.4, g++ 10.2.0, GNU Make 4.3 x86_64-pc-cygwin

<details>
  <summary>Error trace</summary>

```
PS D:\myblog> bundle exec jekyll serve --livereload --trace
Configuration file: D:/myblog/_config.yml
            Source: D:/myblog
       Destination: D:/myblog/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
       Jekyll Feed: Generating feed for posts
                    done in 0.686 seconds.
 Auto-regeneration: enabled for 'D:/myblog'
LiveReload address: http://127.0.0.1:35729
    Server address: http://127.0.0.1:4000/
  Server running... press ctrl-c to stop.
        LiveReload: Browser connected
      Regenerating: 1 file(s) changed at 2021-01-16 12:18:58
                    _posts/2021-01-16-welcome-to-jekyll.markdown
       Jekyll Feed: Generating feed for posts
                    ...done in 0.1560182 seconds.

      Regenerating: 1 file(s) changed at 2021-01-16 12:19:05
                    _posts/2021-01-16-welcome-to-jekyll.markdown
       Jekyll Feed: Generating feed for posts
                    ...done in 0.1454506 seconds.

      Regenerating: 1 file(s) changed at 2021-01-16 12:19:35
                    _posts/2021-01-16-welcome-to-jekyll.markdown
       Jekyll Feed: Generating feed for posts
#<Thread:0x000000000951ba40 D:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/commands/serve/live_reload_reactor.rb:41 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
        7: from D:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/commands/serve/live_reload_reactor.rb:44:in `block in start'
        6: from D:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/eventmachine-1.2.7-x64-mingw32/lib/eventmachine.rb:197:in `run'
        5: from D:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/eventmachine-1.2.7-x64-mingw32/lib/em/pure_ruby.rb:144:in `run_machine'
        4: from D:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/eventmachine-1.2.7-x64-mingw32/lib/em/pure_ruby.rb:547:in `run'
        3: from D:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/eventmachine-1.2.7-x64-mingw32/lib/em/pure_ruby.rb:547:in `loop'
        2: from D:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/eventmachine-1.2.7-x64-mingw32/lib/em/pure_ruby.rb:553:in `block in run'
        1: from D:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/eventmachine-1.2.7-x64-mingw32/lib/em/pure_ruby.rb:595:in `crank_selectables'
D:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/eventmachine-1.2.7-x64-mingw32/lib/em/pure_ruby.rb:595:in `select': An operation was attempted on something that is not a socket. (Errno::ENOTSOCK)
        7: from D:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/commands/serve/live_reload_reactor.rb:44:in `block in start'
        6: from D:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/eventmachine-1.2.7-x64-mingw32/lib/eventmachine.rb:197:in `run'
        5: from D:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/eventmachine-1.2.7-x64-mingw32/lib/em/pure_ruby.rb:144:in `run_machine'
        4: from D:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/eventmachine-1.2.7-x64-mingw32/lib/em/pure_ruby.rb:562:in `run'
        3: from D:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/eventmachine-1.2.7-x64-mingw32/lib/em/pure_ruby.rb:559:in `ensure in run'
        2: from D:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/eventmachine-1.2.7-x64-mingw32/lib/em/pure_ruby.rb:559:in `each'
        1: from D:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/eventmachine-1.2.7-x64-mingw32/lib/em/pure_ruby.rb:559:in `block in run'
D:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/eventmachine-1.2.7-x64-mingw32/lib/em/pure_ruby.rb:559:in `close': Bad file descriptor (Errno::EBADF)
Traceback (most recent call last):
        7: from D:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/commands/serve/live_reload_reactor.rb:44:in `block in start'
        6: from D:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/eventmachine-1.2.7-x64-mingw32/lib/eventmachine.rb:197:in `run'
        5: from D:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/eventmachine-1.2.7-x64-mingw32/lib/em/pure_ruby.rb:144:in `run_machine'
        4: from D:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/eventmachine-1.2.7-x64-mingw32/lib/em/pure_ruby.rb:547:in `run'
        3: from D:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/eventmachine-1.2.7-x64-mingw32/lib/em/pure_ruby.rb:547:in `loop'
        2: from D:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/eventmachine-1.2.7-x64-mingw32/lib/em/pure_ruby.rb:553:in `block in run'
        1: from D:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/eventmachine-1.2.7-x64-mingw32/lib/em/pure_ruby.rb:595:in `crank_selectables'
D:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/eventmachine-1.2.7-x64-mingw32/lib/em/pure_ruby.rb:595:in `select': An operation was attempted on something that is not a socket. (Errno::ENOTSOCK)
        7: from D:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/jekyll-4.2.0/lib/jekyll/commands/serve/live_reload_reactor.rb:44:in `block in start'
        6: from D:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/eventmachine-1.2.7-x64-mingw32/lib/eventmachine.rb:197:in `run'
        5: from D:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/eventmachine-1.2.7-x64-mingw32/lib/em/pure_ruby.rb:144:in `run_machine'
        4: from D:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/eventmachine-1.2.7-x64-mingw32/lib/em/pure_ruby.rb:562:in `run'
        3: from D:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/eventmachine-1.2.7-x64-mingw32/lib/em/pure_ruby.rb:559:in `ensure in run'
        2: from D:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/eventmachine-1.2.7-x64-mingw32/lib/em/pure_ruby.rb:559:in `each'
        1: from D:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/eventmachine-1.2.7-x64-mingw32/lib/em/pure_ruby.rb:559:in `block in run'
D:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/eventmachine-1.2.7-x64-mingw32/lib/em/pure_ruby.rb:559:in `close': Bad file descriptor (Errno::EBADF)
```

</details>

**Comment by vincerubinetti** [comment]
@OverLordGoldDragon Have you seen this issue: https://github.com/oneclick/rubyinstaller2/issues/96 Wondering if it would fix your issues. It seems to (mostly) work for me.

Still, this problem is really needs to be fixed at its root, which seems to be `eventmachine`.

**Comment by lrq3000** [comment]
> It ran fine from a PowerShell window.

That was the key for me, to launch a PowerShell window with admin rights, and it worked. Before, I tried to use the Ruby interpreter and the win Git Bash, none worked. I have a clean Ruby 2.7 install on Windows 10.

**Comment by lrq3000** [comment]
The final solution I've found was to use in a PowerShell:

`jekyll serve --watch`

It's not as good as livereload, but it's better than nothing. Livereload didn't work whatever I tried, including uninstalling eventmanager and reinstalling it specifying the ruby platform.

**Comment by Lojlk** [comment]
> The final solution I've found was to use in a PowerShell:
> 
> `jekyll serve --watch`
> 
> It's not as good as livereload, but it's better than nothing. Livereload didn't work whatever I tried, including uninstalling eventmanager and reinstalling it specifying the ruby platform.

Hey dude, have you tried any solutions since then or still using the same command? Many thanks.

**Comment by Lojlk** [comment]
> @SteveALee
> 
> JFYI, I did get Jekyll running on Windows (`bundle exec jekyll serve --livereload`) with Ruby 2.6.0.
> 
> It did take some wrestling with Bundler, I had to build a gem from a git repo, etc. It ran fine from a PowerShell window.
> 
> It wasn't Jekyll, but some of the dependencies were messy...

Hey Greg, I am currently using  ruby 2.7.5p203 (2021-11-24 revision f69aeb8314) [x64-mingw32], how do I make livereload work? I have tried reinstalling ruby, reinstalling eventmachine with and without --platform ruby. Any new solutions? Many thanks

**Comment by ashmaroli** [comment]
@Lojlk Do you get the *bad file descriptor* error?
I use Jekyll on my Windows system with Ruby 2.7 and Eventmachine built for platform Ruby. Livereload runs fine even though Jekyll's webserver does on rare, non-reproducible occasions, output error messages regarding *`io_fillbuf: fd`* without hampering livereloading or Jekyll's regeneration.

**Comment by Lojlk** [comment]
@ashmaroli 
Hey ash, yes I received the bad file descriptor error. So my issue is that my livereload is not working because of a loadError. C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/eventmachine-1.2.7-x64-mingw32/lib/rubyeventmachine.rb:2:in `require': cannot load such file -- 2.7/rubyeventmachine (LoadError). 

So I added  require 'em/pure_ruby' on to the eventmachine.rb after some googling. 
Unable to load the EventMachine C extension; To use the pure-ruby reactor, require 'em/pure_ruby'

The livereload temporarily worked but after couple of changes, I received a new error which was the bad file descriptor error.

**Comment by ashmaroli** [comment]
@Lojlk The *bad file descriptor* error is weird. I have not been able to understand the cause after all these years..
So I don't have a solution for this thread.

However, your error is different at the moment.
You shouldn't have `gems/eventmachine-1.2.7-x64-mingw32/` if you installed Eventmachine with `--platform=ruby`.
First try uninstalling all versions of eventmachine with `gem uninstall eventmachine` (input *yes* if (any) question(s) are prompted).
Then re-install eventmachine with `--platform=ruby`:
```
gem install eventmachine --platform=ruby
```
In your Jekyll source directory, delete existing `Gemfile.lock`.
Now try serving your site with `--livereload`vas usual.

Based on the comments here, have the site regenerate multiple times to see if you encounter the *bad file descriptor* error.

**Comment by Lojlk** [comment]
@ashmaroli
Hey Ash, OMG! Thank you so much! It is the Gemfile.lock that I needed to delete. You are right with how I shouldn't have the gems/eventmachine-1.2.7-x64-mingw32/ after I installed Eventmachine with --platform=ruby. VScode asked to me reinstall it because it couldn't find the eventmachine-1.2.7-x64-mingw32 folder. This is fantastic! Can I ask why do I have to delete the existing Gemfile.lock? Why did it work after I deleted it?

**Comment by ashmaroli** [comment]
Because the existing `Gemfile.lock` was referencing `eventmachine-x64-mingw32` from an earlier installation.
The new lockfile would now be referencing `eventmachine` (i.e. platform-agnostic version).

Not sure if `bundle update eventmachine` would have worked as well. But deleting the existing lockfile guarantees re-resolution of bundle dependencies.

**Comment by Lojlk** [comment]
@ashmaroli Hey Ash, I ran into another problem. So right now, I am trying to use the github pages on my gem file. Your solution solved the livereload issue, but now the Gemfile is different and it doesn't match the version of "jekyll feed" 
![image](https://user-images.githubusercontent.com/55615416/147866377-a8f9b445-6e34-4e33-834f-5f5fb192ad59.png)

**Comment by ashmaroli** [comment]
@Lojlk The version of GitHub Pages being used is way too old.. (`v36`!!)
Please edit your Gemfile to use a more recent version of GitHub Pages.

*P.S.: This issue is not even remotely related to the topic of this ticket or this repository for that matter.
Please refrain from straying far from the subject of discussion lest posts get flagged as spams.
For usage-related issues about Jekyll, try looking for a solution on the internet first or open a ticket at https://talk.jekyllrb.com/*
