### ISSUE TITLE
send_datagram fails when using periodic timers in a connection

### ISSUE THREAD

**Issue by tpcowan** [eventmachine/eventmachine#888]
I'm in the process of developing an EventMachine datagram server that shares information with multiple devices. I've confirmed the below with ruby 2.5.1 and 2.6.2 and EventMachine 1.2.7. The basic protocol for these devices is to:
1 - send a "hello" message to initialize connection
2 - send a "heartbeat"
3 - re-send the "hello" after a certain amount of time if some condition is met
We accomplish this through the use of an EventMachine::PeriodicTimer which sends a heartbeat and checks the connection at a regular interval.
```ruby

require 'eventmachine'

class Foo < EventMachine::Connection
  def self.create port:, host:
    EventMachine.open_datagram_socket '0.0.0.0', port, self, port: port, host: host
  end

  attr_reader :port, :host

  def initialize port:, host:
    @port = port
    @host = host
    @sequence = 0
    send_hello
    start_timers
  end

  def send_hello
    puts "LOGGING :: START"
    transmit "Hello World"
  end

  def start_timers
    @heartbeat_count = 0
    EventMachine::PeriodicTimer.new(2) do
      transmit "Heartbeat #{sequence}"
      if @heartbeat_count == 5
        puts "LOGGING :: CLOSE"
        @heartbeat_count = 0
        send_hello
      else
        @heartbeat_count += 1
      end
    end
  end

  def sequence
    @sequence += 1
  end

  def transmit data
    puts "TRANSMIT :: #{data} :: pending_connect_timeout is #{pending_connect_timeout}"
    send_datagram data, host, port
  end
end

EM.run do
  Foo.create(port: 5000, host: '192.168.1.201')
end

```
The above logic works well when there is a physical device on the network at the host/port that the datagram is sent to. The normal output from the above code is:
```
LOGGING :: START
TRANSMIT :: Hello World :: pending_connect_timeout is 20.0
...
TRANSMIT :: Heartbeat 6 :: pending_connect_timeout is 20.0
LOGGING :: CLOSE
LOGGING :: START
TRANSMIT :: Hello World :: pending_connect_timeout is 20.0
TRANSMIT :: Heartbeat 7 :: pending_connect_timeout is 20.0
...
TRANSMIT :: Heartbeat 10 :: pending_connect_timeout is 20.0
```
However, when there is no device at the destination address, EventMachine errors.
```
LOGGING :: START
TRANSMIT :: Hello World :: pending_connect_timeout is 20.0
...
TRANSMIT :: Heartbeat 5 :: pending_connect_timeout is 20.0
TRANSMIT :: Heartbeat 6 :: pending_connect_timeout is 0.0
Traceback (most recent call last):
	8: from em_error_test.rb:48:in `<main>'
	7: from /Users/cowan/.rvm/gems/ruby-2.5.1/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run'
	6: from /Users/cowan/.rvm/gems/ruby-2.5.1/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run_machine'
	5: from /Users/cowan/.rvm/gems/ruby-2.5.1/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `call'
	4: from /Users/cowan/.rvm/gems/ruby-2.5.1/gems/eventmachine-1.2.7/lib/em/timers.rb:56:in `fire'
	3: from em_error_test.rb:27:in `block in start_timers'
	2: from em_error_test.rb:44:in `transmit'
	1: from /Users/cowan/.rvm/gems/ruby-2.5.1/gems/eventmachine-1.2.7/lib/em/connection.rb:576:in `send_datagram'
/Users/cowan/.rvm/gems/ruby-2.5.1/gems/eventmachine-1.2.7/lib/em/connection.rb:576:in `send_datagram': error in sending datagram (EventMachine::ConnectionError)
``` 

This behaviour is odd to me since a UDP packet shouldn't be impacted by the physical presence of an endpoint. The  pending_connect_timeout is set to 0.0 just before the error, but I can't find anywhere in my code or in EventMachine where that might occur.

**Comment by mark-a** [comment]
I think this might be a misunderstanding about how UDP and networking works.
While UDP is in fact a stateless protocol, sending packets to a nonexisting IP-Address in the same subnet creates an error on the network interface, since there is no hardware address associated with that IP.

I think you would be happier trying to work with Multicast or Broadcast on the network. 
E.g. see: https://github.com/jpignata/blog/blob/master/articles/multicast-in-ruby.md
