### ISSUE TITLE
undefined symbol: SSLv23_client_method / Unable to load the EventMachine C extension

### ISSUE THREAD

**Issue by jinnko** [eventmachine/eventmachine#892]
EventMachine fails to load on Ubuntu 18.04.  It appears this is due to the fact Ubuntu has removed SSLv2 and SSLv3 support.  Not sure how to work around this.

```
$ which ruby               
/usr/bin/ruby
```

```
$ ruby -v
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]
```

```
$ cat Gemfile
source 'https://rubygems.org' do
  gem 'eventmachine'
end
```

```
$ bundle install               
Fetching gem metadata from https://rubygems.org/.......
Fetching gem metadata from https://rubygems.org/.......
Resolving dependencies...
Fetching binding.repl 3.0.0
Installing binding.repl 3.0.0
Using bundler 2.0.1
Fetching cd 1.0.1
Installing cd 1.0.1
Fetching clipboard 1.3.3
Installing clipboard 1.3.3
Fetching coderay 1.1.2
Installing coderay 1.1.2
Fetching method_source 0.9.2
Installing method_source 0.9.2
Fetching code 0.9.2
Installing code 0.9.2
Fetching paint 2.1.0
Installing paint 2.1.0
Fetching debugging 1.1.1
Installing debugging 1.1.1
Fetching eventmachine 1.2.7
Installing eventmachine 1.2.7 with native extensions
Fetching every_day_irb 2.1.0
Installing every_day_irb 2.1.0
Fetching unicode-display_width 1.6.0
Installing unicode-display_width 1.6.0
Fetching fancy_irb 1.1.0
Installing fancy_irb 1.1.0
Fetching ffi 1.11.1
Installing ffi 1.11.1 with native extensions
Fetching hirb 0.7.3
Installing hirb 0.7.3
Fetching spoon 0.0.6
Installing spoon 0.0.6
Fetching interactive_editor 0.0.11
Installing interactive_editor 0.0.11
Fetching irb 1.0.0
Installing irb 1.0.0
Fetching methodfinder 2.2.1
Installing methodfinder 2.2.1
Fetching object_shadow 1.1.0
Installing object_shadow 1.1.0
Fetching ori 0.1.0
Installing ori 0.1.0
Fetching os 1.0.1
Installing os 1.0.1
Fetching ruby_engine 1.0.1
Installing ruby_engine 1.0.1
Fetching ruby_info 1.0.1
Installing ruby_info 1.0.1
Fetching ruby_version 1.0.1
Installing ruby_version 1.0.1
Fetching wirb 2.1.2
Installing wirb 2.1.2
Fetching irbtools 3.0.0
Installing irbtools 3.0.0
Bundle complete! 2 Gemfile dependencies, 27 gems now installed.
Bundled gems are installed into `./.bundle`
```

```
$ bundle exec irb                           
Welcome to IRB. You are using ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]. Have fun ;)
>> require 'eventmachine'
Unable to load the EventMachine C extension; To use the pure-ruby reactor, require 'em/pure_ruby'
Traceback (most recent call last):
        7: from /tmp/.bundle/ruby/2.5.0/bin/irb:23:in `<main>'
        6: from /tmp/.bundle/ruby/2.5.0/bin/irb:23:in `load'
        5: from /tmp/.bundle/ruby/2.5.0/gems/irb-1.0.0/exe/irb:11:in `<top (required)>'
        4: from (irb):1
        3: from (irb):1:in `require'
        2: from /tmp/.bundle/ruby/2.5.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:8:in `<top (required)>'
        1: from /tmp/.bundle/ruby/2.5.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:8:in `require'
LoadError (/tmp/.bundle/ruby/2.5.0/gems/eventmachine-1.2.7/lib/rubyeventmachine.so: undefined symbol: SSLv23_client_method - /tmp/.bundle/ruby/2.5.0/gems/eventmachine-1.2.7/lib/rubyeventmachine.so)
```

**Comment by MSP-Greg** [comment]
@jinnko 

PR #893 should solve this.  It passes on bionic 18.04 with Ruby 2.6.3...
