### ISSUE TITLE
eventmachine not initialized: evma_release_library in truffleruby

### ISSUE THREAD

**Issue by dgolosow** [eventmachine/eventmachine#902]
Is EventMachine usable with truffleruby?  Getting the following error: 
``` bash
#<Thread:0x2368@(irb):2 run> terminated with exception:
/usr/local/rvm/rubies/truffleruby-19.2.0.1/lib/truffle/truffle/cext.rb:1160:in `rb_exc_raise': eventmachine not initialized: evma_release_library (RuntimeError)
        from ruby.c:2089:in `rb_exc_raise'
        from /usr/local/rvm/gems/truffleruby-19.2.0.1/gems/eventmachine-1.3.0.dev.1/ext/cmain.cpp:41:in `ensure_eventmachine'
        from /usr/local/rvm/gems/truffleruby-19.2.0.1/gems/eventmachine-1.3.0.dev.1/ext/cmain.cpp:71:in `evma_release_library'
        from /usr/local/rvm/gems/truffleruby-19.2.0.1/gems/eventmachine-1.3.0.dev.1/ext/rubymain.cpp:884:in `t_release_machine'
        from /usr/local/rvm/rubies/truffleruby-19.2.0.1/lib/truffle/truffle/cext_ruby.rb:37:in `release_machine'                
        from /usr/local/rvm/gems/truffleruby-19.2.0.1/gems/eventmachine-1.3.0.dev.1/lib/eventmachine.rb:204:in `run'            
        from (irb):2:in `block in irb_binding'
```

**Comment by eregon** [comment]
Interesting, how did you install eventmachine? From source?

**Comment by sodabrew** [comment]
I've never tried it with TruffleRuby, but I'm open to pull requests if support is not too hard to add!

**Comment by eregon** [comment]
I think this issue is basically the same as https://github.com/oracle/truffleruby/issues/1623.
i.e., the real error is `rb_fd_init` is not yet implemented on TruffleRuby.

**Comment by sodabrew** [comment]
https://github.com/oracle/truffleruby/issues/1623 was closed as implemented, so I'm going to close this ticket, too.
