### ISSUE TITLE
Compatable w/ openssl1.1?

### ISSUE THREAD

**Issue by joelcahalan** [eventmachine/eventmachine#904]
Getting the follwoing error using Guard:
`Unable to load the EventMachine C extension; To use the pure-ruby reactor, require 'em/pure_ruby'
16:41:38 - ERROR - Could not load 'guard/livereload' or find class Guard::Livereload
16:41:38 - ERROR - Error is: dlopen(/Users/joel/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/eventmachine-1.2.7/lib/rubyeventmachine.bundle, 9): Library not loaded: /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib
> [#]   Referenced from: /Users/joel/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/eventmachine-1.2.7/lib/rubyeventmachine.bundle
> [#]   Reason: image not found - /Users/joel/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/eventmachine-1.2.7/lib/rubyeventmachine.bundle
16:41:38 - ERROR - /Users/joel/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:8:in `require'
> [#] /Users/joel/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:8:in `<top (required)>'`

Do I need to downgrade my openssl or is there another workaround?

**Comment by sodabrew** [comment]
You have to have the same library version of openssl at runtime as you compiled with.

**Comment by joelcahalan** [comment]
@sodabrew, thanks for the explanation.  I am not familiar with the compile process. Does that happen locally when I install the gem? Is the solution to delete and reinstall?

**Comment by joelcahalan** [comment]
The solution was a simple `gem uninstall eventmachine` and then `bundle`.  Thanks!

**Comment by MSP-Greg** [comment]
For newer versions of Ruby, the following code should show the same numeric version for all four items.  Also, OpenSSL 1.0.2 is EOL, so ideally one should be using 1.1.1.

```ruby
require 'openssl'
require 'eventmachine'
puts "OpenSSL OPENSSL_LIBRARY_VERSION: #{OpenSSL::OPENSSL_LIBRARY_VERSION}\n" \
     "                OPENSSL_VERSION: #{OpenSSL::OPENSSL_VERSION}\n"         \
     "     EM OPENSSL_LIBRARY_VERSION: #{EM::OPENSSL_LIBRARY_VERSION}\n"      \
     "                OPENSSL_VERSION: #{EM::OPENSSL_VERSION
```
