### ISSUE TITLE
ruby 2.6.5p114 (2019-10-01 revision 67812) - eventmachine-1.2.7 - Segmentation fault at 0x0000000000000141

### ISSUE THREAD

**Issue by aledav** [eventmachine/eventmachine#908]
Hi, I've encountered this error using eventmachine and em-http-request.
It seems to occur after several errback from the HttpRequest, below is the post-mortem and the sample code used.

```
        def self.log(session_id, log_level, content)
            return if LOG_LEVEL[Settings.log&.level] && LOG_LEVEL[log_level] < LOG_LEVEL[Settings.log.level]
            content = filtered_params(content).to_json if content.is_a?(Hash)
            puts "#{Time.now.utc} #{log_level}: #{content}"
            EventMachine.run {
                http = EventMachine::HttpRequest.new(EVENT_LOGGER_URL, base_http_options).post(
                    path: '/api/log',
                    body: body(session_id, log_level, content).to_json,
                    head: { "Content-Type": "application/json" }
                )
                http.errback {
                    say "An error occured while trying to connect to the logger."
                    EventMachine.stop
                }
                http.callback {
                    if http.response_header.status != 200
                        say "Tried logging but event logger responded with http code #{http.response_header.status} : #{http.response}"
                    end
                    EventMachine.stop
                }
            }
        end
```

```
web_1    | /usr/local/bundle/gems/eventmachine-1.2.7/lib/eventmachine.rb:195: [BUG] Segmentation fault at 0x0000000000000141
web_1    | ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux]
web_1    | 
web_1    | -- Control frame information -----------------------------------------------
web_1    | c:0068 p:---- s:0490 e:000489 CFUNC  :run_machine
web_1    | c:0067 p:0275 s:0486 e:000485 METHOD /usr/local/bundle/gems/eventmachine-1.2.7/lib/eventmachine.rb:195
web_1    | c:0066 p:0164 s:0478 E:000488 METHOD /cb4xb2b2c/lib/bca_logger.rb:52
web_1    | c:0065 p:0015 s:0471 e:000470 METHOD /cb4xb2b2c/lib/bca_logger.rb:23
web_1    | c:0064 p:0079 s:0465 e:000464 METHOD /cb4xb2b2c/app/controllers/application_controller.rb:32
web_1    | c:0063 p:0036 s:0461 e:000460 BLOCK  /usr/local/bundle/gems/activesupport-6.0.1/lib/active_support/callbacks.rb:429
web_1    | c:0062 p:0011 s:0453 e:000452 BLOCK  /usr/local/bundle/gems/activesupport-6.0.1/lib/active_support/callbacks.rb:201
web_1    | c:0061 p:0006 s:0450 e:000449 BLOCK  /usr/local/bundle/gems/actionpack-6.0.1/lib/abstract_controller/callbacks.rb:34
web_1    | c:0060 p:0045 s:0445 E:000748 BLOCK  /usr/local/bundle/gems/activesupport-6.0.1/lib/active_support/callbacks.rb:202
web_1    | c:0059 p:0008 s:0436 e:000435 BLOCK  /usr/local/bundle/gems/activesupport-6.0.1/lib/active_support/callbacks.rb:514 [FINISH]
web_1    | c:0058 p:---- s:0432 e:000431 CFUNC  :each
web_1    | c:0057 p:0007 s:0428 e:000427 METHOD /usr/local/bundle/gems/activesupport-6.0.1/lib/active_support/callbacks.rb:514
web_1    | c:0056 p:0085 s:0423 E:0023e8 METHOD /usr/local/bundle/gems/activesupport-6.0.1/lib/active_support/callbacks.rb:134
web_1    | c:0055 p:0007 s:0414 E:000238 METHOD /usr/local/bundle/gems/actionpack-6.0.1/lib/abstract_controller/callbacks.rb:41
web_1    | c:0054 p:0009 s:0409 e:000408 METHOD /usr/local/bundle/gems/actionpack-6.0.1/lib/action_controller/metal/rescue.rb:22
web_1    | c:0053 p:0010 s:0403 e:000402 BLOCK  /usr/local/bundle/gems/actionpack-6.0.1/lib/action_controller/metal/instrumentation.rb:33
web_1    | c:0052 p:0011 s:0399 e:000398 BLOCK  /usr/local/bundle/gems/activesupport-6.0.1/lib/active_support/notifications.rb:180
web_1    | c:0051 p:0024 s:0396 e:000395 METHOD /usr/local/bundle/gems/activesupport-6.0.1/lib/active_support/notifications/instrumenter.rb:24
web_1    | c:0050 p:0027 s:0388 e:000387 METHOD /usr/local/bundle/gems/activesupport-6.0.1/lib/active_support/notifications.rb:180
web_1    | c:0049 p:0104 s:0382 e:000381 METHOD /usr/local/bundle/gems/actionpack-6.0.1/lib/action_controller/metal/instrumentation.rb:32
web_1    | c:0048 p:0020 s:0376 e:000375 METHOD /usr/local/bundle/gems/actionpack-6.0.1/lib/action_controller/metal/params_wrapper.rb:245
web_1    | c:0047 p:0024 s:0371 e:000370 METHOD /usr/local/bundle/gems/activerecord-6.0.1/lib/active_record/railties/controller_runtime.rb:27
web_1    | c:0046 p:0083 s:0365 e:000364 METHOD /usr/local/bundle/gems/actionpack-6.0.1/lib/abstract_controller/base.rb:136
web_1    | c:0045 p:0060 s:0358 e:000357 METHOD /usr/local/bundle/gems/actionview-6.0.1/lib/action_view/rendering.rb:39
web_1    | c:0044 p:0020 s:0352 e:000351 METHOD /usr/local/bundle/gems/actionpack-6.0.1/lib/action_controller/metal.rb:191
web_1    | c:0043 p:0042 s:0345 e:000344 METHOD /usr/local/bundle/gems/actionpack-6.0.1/lib/action_controller/metal.rb:252
web_1    | c:0042 p:0011 s:0338 e:000337 METHOD /usr/local/bundle/gems/actionpack-6.0.1/lib/action_dispatch/routing/route_set.rb:51
web_1    | c:0041 p:0041 s:0330 e:000329 METHOD /usr/local/bundle/gems/actionpack-6.0.1/lib/action_dispatch/routing/route_set.rb:33
web_1    | c:0040 p:0135 s:0322 e:000321 BLOCK  /usr/local/bundle/gems/actionpack-6.0.1/lib/action_dispatch/journey/router.rb:49 [FINISH]
web_1    | c:0039 p:---- s:0310 e:000309 CFUNC  :each
web_1    | c:0038 p:0010 s:0306 e:000305 METHOD /usr/local/bundle/gems/actionpack-6.0.1/lib/action_dispatch/journey/router.rb:32
web_1    | c:0037 p:0041 s:0301 e:000300 METHOD /usr/local/bundle/gems/actionpack-6.0.1/lib/action_dispatch/routing/route_set.rb:837
web_1    | c:0036 p:0036 s:0295 e:000294 METHOD /usr/local/bundle/gems/rack-2.0.7/lib/rack/tempfile_reaper.rb:15
web_1    | c:0035 p:0008 s:0286 e:000285 METHOD /usr/local/bundle/gems/rack-2.0.7/lib/rack/etag.rb:25
web_1    | c:0034 p:0049 s:0275 e:000274 METHOD /usr/local/bundle/gems/rack-2.0.7/lib/rack/conditional_get.rb:25
web_1    | c:0033 p:0008 s:0266 e:000265 METHOD /usr/local/bundle/gems/rack-2.0.7/lib/rack/head.rb:12
web_1    | c:0032 p:0024 s:0258 e:000257 METHOD /usr/local/bundle/gems/actionpack-6.0.1/lib/action_dispatch/http/content_security_policy.rb:18
web_1    | c:0031 p:0030 s:0245 e:000244 METHOD /usr/local/bundle/gems/rack-2.0.7/lib/rack/session/abstract/id.rb:232
web_1    | c:0030 p:0006 s:0234 e:000233 METHOD /usr/local/bundle/gems/rack-2.0.7/lib/rack/session/abstract/id.rb:226
web_1    | c:0029 p:0024 s:0229 e:000228 METHOD /usr/local/bundle/gems/actionpack-6.0.1/lib/action_dispatch/middleware/cookies.rb:648
web_1    | c:0028 p:0009 s:0219 e:000218 BLOCK  /usr/local/bundle/gems/actionpack-6.0.1/lib/action_dispatch/middleware/callbacks.rb:27
web_1    | c:0027 p:0029 s:0216 e:000215 METHOD /usr/local/bundle/gems/activesupport-6.0.1/lib/active_support/callbacks.rb:101
web_1    | c:0026 p:0010 s:0207 e:000206 METHOD /usr/local/bundle/gems/actionpack-6.0.1/lib/action_dispatch/middleware/callbacks.rb:26
web_1    | c:0025 p:0032 s:0200 e:000199 METHOD /usr/local/bundle/gems/actionpack-6.0.1/lib/action_dispatch/middleware/actionable_exceptions.rb:17
web_1    | c:0024 p:0024 s:0194 e:000193 METHOD /usr/local/bundle/gems/actionpack-6.0.1/lib/action_dispatch/middleware/debug_exceptions.rb:32
web_1    | c:0023 p:0024 s:0183 e:000182 METHOD /usr/local/bundle/gems/actionpack-6.0.1/lib/action_dispatch/middleware/show_exceptions.rb:33
web_1    | c:0022 p:0042 s:0176 e:000175 METHOD /usr/local/bundle/gems/railties-6.0.1/lib/rails/rack/logger.rb:38
web_1    | c:0021 p:0009 s:0166 e:000165 BLOCK  /usr/local/bundle/gems/railties-6.0.1/lib/rails/rack/logger.rb:26
web_1    | c:0020 p:0004 s:0163 e:000162 BLOCK  /usr/local/bundle/gems/activesupport-6.0.1/lib/active_support/tagged_logging.rb:80
web_1    | c:0019 p:0013 s:0160 e:000159 METHOD /usr/local/bundle/gems/activesupport-6.0.1/lib/active_support/tagged_logging.rb:28
web_1    | c:0018 p:0012 s:0154 e:000153 METHOD /usr/local/bundle/gems/activesupport-6.0.1/lib/active_support/tagged_logging.rb:80
web_1    | c:0017 p:0041 s:0149 e:000148 METHOD /usr/local/bundle/gems/railties-6.0.1/lib/rails/rack/logger.rb:26
web_1    | c:0016 p:0053 s:0143 e:000142 METHOD /usr/local/bundle/gems/actionpack-6.0.1/lib/action_dispatch/middleware/remote_ip.rb:81
web_1    | c:0015 p:0039 s:0137 e:000136 METHOD /usr/local/bundle/gems/actionpack-6.0.1/lib/action_dispatch/middleware/request_id.rb:27
web_1    | c:0014 p:0091 s:0131 e:000130 METHOD /usr/local/bundle/gems/rack-2.0.7/lib/rack/method_override.rb:22
web_1    | c:0013 p:0020 s:0125 e:000124 METHOD /usr/local/bundle/gems/rack-2.0.7/lib/rack/runtime.rb:22
web_1    | c:0012 p:0033 s:0115 e:000114 METHOD /usr/local/bundle/gems/activesupport-6.0.1/lib/active_support/cache/strategy/local_cache_middleware.rb:29
web_1    | c:0011 p:0016 s:0108 e:000107 METHOD /usr/local/bundle/gems/actionpack-6.0.1/lib/action_dispatch/middleware/executor.rb:14
web_1    | c:0010 p:0083 s:0100 e:000099 METHOD /usr/local/bundle/gems/actionpack-6.0.1/lib/action_dispatch/middleware/static.rb:126
web_1    | c:0009 p:0008 s:0092 e:000091 METHOD /usr/local/bundle/gems/rack-2.0.7/lib/rack/sendfile.rb:111
web_1    | c:0008 p:0054 s:0080 e:000079 METHOD /usr/local/bundle/gems/actionpack-6.0.1/lib/action_dispatch/middleware/host_authorization.rb:83
web_1    | c:0007 p:0020 s:0074 e:000073 METHOD /usr/local/bundle/gems/railties-6.0.1/lib/rails/engine.rb:526
web_1    | c:0006 p:0026 s:0068 e:000067 METHOD /usr/local/bundle/gems/puma-4.3.0/lib/puma/configuration.rb:228
web_1    | c:0005 p:0263 s:0063 e:000062 METHOD /usr/local/bundle/gems/puma-4.3.0/lib/puma/server.rb:667
web_1    | c:0004 p:0026 s:0038 e:000037 METHOD /usr/local/bundle/gems/puma-4.3.0/lib/puma/server.rb:470
web_1    | c:0003 p:0065 s:0026 e:000025 BLOCK  /usr/local/bundle/gems/puma-4.3.0/lib/puma/server.rb:328
web_1    | c:0002 p:0107 s:0016 e:000015 BLOCK  /usr/local/bundle/gems/puma-4.3.0/lib/puma/thread_pool.rb:134 [FINISH]
web_1    | c:0001 p:---- s:0003 e:000002 (none) [FINISH]
web_1    | 
web_1    | -- Ruby level backtrace information ----------------------------------------
web_1    | /usr/local/bundle/gems/puma-4.3.0/lib/puma/thread_pool.rb:134:in `block in spawn_thread'
web_1    | /usr/local/bundle/gems/puma-4.3.0/lib/puma/server.rb:328:in `block in run'
web_1    | /usr/local/bundle/gems/puma-4.3.0/lib/puma/server.rb:470:in `process_client'
web_1    | /usr/local/bundle/gems/puma-4.3.0/lib/puma/server.rb:667:in `handle_request'
web_1    | /usr/local/bundle/gems/puma-4.3.0/lib/puma/configuration.rb:228:in `call'
web_1    | /usr/local/bundle/gems/railties-6.0.1/lib/rails/engine.rb:526:in `call'
web_1    | /usr/local/bundle/gems/actionpack-6.0.1/lib/action_dispatch/middleware/host_authorization.rb:83:in `call'
web_1    | /usr/local/bundle/gems/rack-2.0.7/lib/rack/sendfile.rb:111:in `call'
web_1    | /usr/local/bundle/gems/actionpack-6.0.1/lib/action_dispatch/middleware/static.rb:126:in `call'
web_1    | /usr/local/bundle/gems/actionpack-6.0.1/lib/action_dispatch/middleware/executor.rb:14:in `call'
web_1    | /usr/local/bundle/gems/activesupport-6.0.1/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
web_1    | /usr/local/bundle/gems/rack-2.0.7/lib/rack/runtime.rb:22:in `call'
web_1    | /usr/local/bundle/gems/rack-2.0.7/lib/rack/method_override.rb:22:in `call'
web_1    | /usr/local/bundle/gems/actionpack-6.0.1/lib/action_dispatch/middleware/request_id.rb:27:in `call'
web_1    | /usr/local/bundle/gems/actionpack-6.0.1/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
web_1    | /usr/local/bundle/gems/railties-6.0.1/lib/rails/rack/logger.rb:26:in `call'
web_1    | /usr/local/bundle/gems/activesupport-6.0.1/lib/active_support/tagged_logging.rb:80:in `tagged'
web_1    | /usr/local/bundle/gems/activesupport-6.0.1/lib/active_support/tagged_logging.rb:28:in `tagged'
web_1    | /usr/local/bundle/gems/activesupport-6.0.1/lib/active_support/tagged_logging.rb:80:in `block in tagged'
web_1    | /usr/local/bundle/gems/railties-6.0.1/lib/rails/rack/logger.rb:26:in `block in call'
web_1    | /usr/local/bundle/gems/railties-6.0.1/lib/rails/rack/logger.rb:38:in `call_app'
web_1    | /usr/local/bundle/gems/actionpack-6.0.1/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
web_1    | /usr/local/bundle/gems/actionpack-6.0.1/lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
web_1    | /usr/local/bundle/gems/actionpack-6.0.1/lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
web_1    | /usr/local/bundle/gems/actionpack-6.0.1/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
web_1    | /usr/local/bundle/gems/activesupport-6.0.1/lib/active_support/callbacks.rb:101:in `run_callbacks'
web_1    | /usr/local/bundle/gems/actionpack-6.0.1/lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
web_1    | /usr/local/bundle/gems/actionpack-6.0.1/lib/action_dispatch/middleware/cookies.rb:648:in `call'
web_1    | /usr/local/bundle/gems/rack-2.0.7/lib/rack/session/abstract/id.rb:226:in `call'
web_1    | /usr/local/bundle/gems/rack-2.0.7/lib/rack/session/abstract/id.rb:232:in `context'
web_1    | /usr/local/bundle/gems/actionpack-6.0.1/lib/action_dispatch/http/content_security_policy.rb:18:in `call'
web_1    | /usr/local/bundle/gems/rack-2.0.7/lib/rack/head.rb:12:in `call'
web_1    | /usr/local/bundle/gems/rack-2.0.7/lib/rack/conditional_get.rb:25:in `call'
web_1    | /usr/local/bundle/gems/rack-2.0.7/lib/rack/etag.rb:25:in `call'
web_1    | /usr/local/bundle/gems/rack-2.0.7/lib/rack/tempfile_reaper.rb:15:in `call'
web_1    | /usr/local/bundle/gems/actionpack-6.0.1/lib/action_dispatch/routing/route_set.rb:837:in `call'
web_1    | /usr/local/bundle/gems/actionpack-6.0.1/lib/action_dispatch/journey/router.rb:32:in `serve'
web_1    | /usr/local/bundle/gems/actionpack-6.0.1/lib/action_dispatch/journey/router.rb:32:in `each'
web_1    | /usr/local/bundle/gems/actionpack-6.0.1/lib/action_dispatch/journey/router.rb:49:in `block in serve'
web_1    | /usr/local/bundle/gems/actionpack-6.0.1/lib/action_dispatch/routing/route_set.rb:33:in `serve'
web_1    | /usr/local/bundle/gems/actionpack-6.0.1/lib/action_dispatch/routing/route_set.rb:51:in `dispatch'
web_1    | /usr/local/bundle/gems/actionpack-6.0.1/lib/action_controller/metal.rb:252:in `dispatch'
web_1    | /usr/local/bundle/gems/actionpack-6.0.1/lib/action_controller/metal.rb:191:in `dispatch'
web_1    | /usr/local/bundle/gems/actionview-6.0.1/lib/action_view/rendering.rb:39:in `process'
web_1    | /usr/local/bundle/gems/actionpack-6.0.1/lib/abstract_controller/base.rb:136:in `process'
web_1    | /usr/local/bundle/gems/activerecord-6.0.1/lib/active_record/railties/controller_runtime.rb:27:in `process_action'
web_1    | /usr/local/bundle/gems/actionpack-6.0.1/lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
web_1    | /usr/local/bundle/gems/actionpack-6.0.1/lib/action_controller/metal/instrumentation.rb:32:in `process_action'
web_1    | /usr/local/bundle/gems/activesupport-6.0.1/lib/active_support/notifications.rb:180:in `instrument'
web_1    | /usr/local/bundle/gems/activesupport-6.0.1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
web_1    | /usr/local/bundle/gems/activesupport-6.0.1/lib/active_support/notifications.rb:180:in `block in instrument'
web_1    | /usr/local/bundle/gems/actionpack-6.0.1/lib/action_controller/metal/instrumentation.rb:33:in `block in process_action'
web_1    | /usr/local/bundle/gems/actionpack-6.0.1/lib/action_controller/metal/rescue.rb:22:in `process_action'
web_1    | /usr/local/bundle/gems/actionpack-6.0.1/lib/abstract_controller/callbacks.rb:41:in `process_action'
web_1    | /usr/local/bundle/gems/activesupport-6.0.1/lib/active_support/callbacks.rb:134:in `run_callbacks'
web_1    | /usr/local/bundle/gems/activesupport-6.0.1/lib/active_support/callbacks.rb:514:in `invoke_before'
web_1    | /usr/local/bundle/gems/activesupport-6.0.1/lib/active_support/callbacks.rb:514:in `each'
web_1    | /usr/local/bundle/gems/activesupport-6.0.1/lib/active_support/callbacks.rb:514:in `block in invoke_before'
web_1    | /usr/local/bundle/gems/activesupport-6.0.1/lib/active_support/callbacks.rb:202:in `block in halting'
web_1    | /usr/local/bundle/gems/actionpack-6.0.1/lib/abstract_controller/callbacks.rb:34:in `block (2 levels) in <module:Callbacks>'
web_1    | /usr/local/bundle/gems/activesupport-6.0.1/lib/active_support/callbacks.rb:201:in `block (2 levels) in halting'
web_1    | /usr/local/bundle/gems/activesupport-6.0.1/lib/active_support/callbacks.rb:429:in `block in make_lambda'
web_1    | /cb4xb2b2c/app/controllers/application_controller.rb:32:in `set_session_id!'
web_1    | /cb4xb2b2c/lib/bca_logger.rb:23:in `info'
web_1    | /cb4xb2b2c/lib/bca_logger.rb:52:in `log'
web_1    | /usr/local/bundle/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run'
web_1    | /usr/local/bundle/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run_machine'
web_1    | 
web_1    | -- Machine register context ------------------------------------------------
web_1    |  RIP: 0x0000000000000141 RBP: 0x00007fd1c83fa650 RSP: 0x00007fd1cfbf9dc8
web_1    |  RAX: 0x00007fd1c8276c30 RBX: 0x0000000000000008 RCX: 0x00007fd1c82606e8
web_1    |  RDX: 0x0000000000000001 RDI: 0x00007fd1c8000090 RSI: 0x00007fd1d8711620
web_1    |   R8: 0x0000000000000000  R9: 0x0000000000000000 R10: 0x00007fd1c800d840
web_1    |  R11: 0x0000000000000000 R12: 0x0000000000000000 R13: 0x0000000000000008
web_1    |  R14: 0x00007fd1cfbf9dd8 R15: 0x00005643d9515c98 EFL: 0x0000000000010206
web_1    | 
web_1    | -- C level backtrace information -------------------------------------------
```

**Comment by sodabrew** [comment]
Is this logging function part of a larger service that uses EventMachine? If you're already inside the machine, you shouldn't have an EM.run inside the one method. Rather, the logger method itself should be defined in terms of callbacks.

**Comment by aledav** [comment]
This function wasn't part of a service using EM, it was the only place we were using it. We have since discarded this feature since we no longer use a remote logging service so I won't be able to reproduce if needed.
