### ISSUE TITLE
Is EM_PURE_RUBY mode supported?

### ISSUE THREAD

**Issue by voxik** [eventmachine/eventmachine#924]
There used to be pure ruby mode of EM. However, the test suite is not executed anywhere AFAIK neither it works by my brief testing:

~~~
Traceback (most recent call last):
	9: from -e:1:in `<main>'
	8: from -e:1:in `each'
	7: from -e:1:in `block in <main>'
	6: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:83:in `require'
	5: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:83:in `require'
	4: from /builddir/build/BUILD/eventmachine-1.2.7/usr/share/gems/gems/eventmachine-1.2.7/tests/test_pure.rb:1:in `<top (required)>'
	3: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:83:in `require'
	2: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:83:in `require'
	1: from /builddir/build/BUILD/eventmachine-1.2.7/usr/share/gems/gems/eventmachine-1.2.7/tests/em_test_helper.rb:7:in `<top (required)>'
/builddir/build/BUILD/eventmachine-1.2.7/usr/share/gems/gems/eventmachine-1.2.7/tests/em_test_helper.rb:19:in `<class:TestCase>': uninitialized constant EventMachine::OPENSSL_LIBRARY_VERSION (NameError)
~~~

and it seems the test for `EM::OPENSSL_LIBRARY_VERSION` is on more places.

Therefore I wonder if the pure ruby mode is supported. If yes, it would be nice to test it and if not, may be it should be dropped altogether.

**Comment by MSP-Greg** [comment]
> pure ruby mode... it would be nice to test

I apologize for that, assuming MRI and/or that OpenSSL is available.  I'll get a CI job running with pure Ruby EM and check the OpenSSL issues.

**Comment by sodabrew** [comment]
The test suite does not complete all tests for the pure ruby module. It's not been a priority to complete the implementation. PRs welcome!

**Comment by voxik** [comment]
> The test suite does not complete all tests for the pure ruby module. It's not been a priority to complete the implementation.

That is alright. But currently the test suite crashes even before the first test is executed.

**Comment by nevans** [comment]
FYI, I have a PR that gets tests passing for pure ruby mode here: #993.  I can't promise that pure ruby mode has full parity (it almost certainly does *not*).  But the tests all pass... on Linux (there are still a few issues with MacOS and Windows).
