### ISSUE TITLE
Install failed on ruby 2.7.2 and gcc 11

### ISSUE THREAD

**Issue by junaruga** [eventmachine/eventmachine#942]
I failed to install eventmachine latest version 1.2.7 on Fedora 32, gcc 11.0.0, ruby 2.7.2. 
The gcc is installed from Fedora 35 (rawhide). It's not really a usual environment.

```
$ gem install eventmachine
Fetching eventmachine-1.2.7.gem
Building native extensions. This could take a while...
ERROR:  Error installing eventmachine:
	ERROR: Failed to build gem native extension.
```

Could you take look at the following steps?
Thank you.

```
$ cat /etc/fedora-release 
Fedora release 32 (Thirty Two)

$ gcc --version
gcc (GCC) 11.0.0 20210210 (Red Hat 11.0.0-0)
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ rpm -q gcc
gcc-11.0.0-0.19.fc35.x86_64

$ rpm -q openssl-devel
openssl-devel-1.1.1i-1.fc32.x86_64

$ ruby -v
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux]
[fedora@ci-vm-10-0-138-134 mysql2]$ which ruby
/usr/bin/ruby

$ rpm -q ruby
ruby-2.7.2-135.fc32.x86_64

$ rpm -q ruby-devel
ruby-devel-2.7.2-135.fc32.x86_64

$ gem install eventmachine
Fetching eventmachine-1.2.7.gem
Building native extensions. This could take a while...
ERROR:  Error installing eventmachine:
	ERROR: Failed to build gem native extension.

    current directory: /home/fedora/.gem/ruby/gems/eventmachine-1.2.7/ext
/usr/bin/ruby -I /usr/share/rubygems -r ./siteconf20210218-12400-camjtr.rb extconf.rb
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib64
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/bin/$(RUBY_BASE_NAME)
	--with-ssl-dir
	--without-ssl-dir
	--with-ssl-include
	--without-ssl-include=${ssl-dir}/include
	--with-ssl-lib
	--without-ssl-lib=${ssl-dir}/lib64
	--with-openssl-config
	--without-openssl-config
	--with-pkg-config
	--without-pkg-config
/usr/share/ruby/mkmf.rb:471:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /usr/share/ruby/mkmf.rb:564:in `try_link0'
	from /usr/share/ruby/mkmf.rb:582:in `try_link'
	from /usr/share/ruby/mkmf.rb:684:in `try_ldflags'
	from /usr/share/ruby/mkmf.rb:1851:in `pkg_config'
	from extconf.rb:65:in `pkg_config_wrapper'
	from extconf.rb:92:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /home/fedora/.gem/ruby/extensions/x86_64-linux/2.7.0/eventmachine-1.2.7/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /home/fedora/.gem/ruby/gems/eventmachine-1.2.7 for inspection.
Results logged to /home/fedora/.gem/ruby/extensions/x86_64-linux/2.7.0/eventmachine-1.2.7/gem_make.out
```

```
$ cat /home/fedora/.gem/ruby/extensions/x86_64-linux/2.7.0/eventmachine-1.2.7/mkmf.log
"gcc -o conftest -I/usr/include -I/usr/include/ruby/backward -I/usr/include -I.    -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fPIC conftest.c  -L. -L/usr/lib64 -L. -Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -fstack-protector-strong -rdynamic -Wl,-export-dynamic  -m64   -lruby  -lm   -lc"
as: unrecognized option '--gdwarf-5'
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: int main(int argc, char **argv)
4: {
5:   return !!argv[argc];
6: }
/* end */

"pkg-config --exists openssl"
| pkg-config --libs openssl
=> "-lssl -lcrypto \n"
```

**Comment by junaruga** [comment]
On the Fedora 35 with ruby 3.0 and gcc 11.0.0, eventmachine was installed successfully.

```
$ cat /etc/fedora-release 
Fedora release 35 (Rawhide)

$ gcc --version
gcc (GCC) 11.0.0 20210210 (Red Hat 11.0.0-0)
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ ruby -v
ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-linux]

$ gem install eventmachine
Fetching eventmachine-1.2.7.gem
Building native extensions. This could take a while...
Successfully installed eventmachine-1.2.7
Parsing documentation for eventmachine-1.2.7
Installing ri documentation for eventmachine-1.2.7
Done installing documentation for eventmachine after 4 seconds
1 gem installed
```

**Comment by junaruga** [comment]
Sorry something wrong on the Fedora 32 environment. I would close this ticket.

```
$ cat /etc/fedora-release 
Fedora release 32 (Thirty Two)
```

```
$ cat conftest.c 
int main(int argc, char **argv)
{
  return !!argv[argc];
}
```

```
$ gcc -o conftest -I/usr/include -I/usr/include/ruby/backward -I/usr/include -I.    -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fPIC conftest.c  -L. -L/usr/lib64 -L. -Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -fstack-protector-strong -rdynamic -Wl,-export-dynamic  -m64   -lruby  -lm   -lc
as: unrecognized option '--gdwarf-5'

$ echo $?
2
```

**Comment by junaruga** [comment]
A minimal reproducer.

```
$ gcc -o conftest -g conftest.c 
as: unrecognized option '--gdwarf-5'

$ echo $?
1
```
