### ISSUE TITLE
Issue on Ruby 3.0.4

### ISSUE THREAD

**Issue by BertZZ** [eventmachine/eventmachine#969]
Hi, when I try to enter the rails console using ruby 3.0.4 I run in to this error. I am using a new M1 macbook pro. Any suggestions would be great. I have already unistalled and reinstalled the gem

```
Unable to load the EventMachine C extension; To use the pure-ruby reactor, require 'em/pure_ruby'
rake aborted!
LoadError: dlopen(/Users/bertie/.rvm/gems/ruby-3.0.4/gems/eventmachine-1.2.7/lib/rubyeventmachine.bundle, 0x0009): symbol not found in flat namespace '_SSL_get1_peer_certificate' - /Users/bertie/.rvm/gems/ruby-3.0.4/gems/eventmachine-1.2.7/lib/rubyeventmachine.bundle
/Users/bertie/.rvm/gems/ruby-3.0.4/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/Users/bertie/.rvm/gems/ruby-3.0.4/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/Users/bertie/.rvm/gems/ruby-3.0.4/gems/activesupport-6.1.5.1/lib/active_support/dependencies.rb:332:in `block in require'
/Users/bertie/.rvm/gems/ruby-3.0.4/gems/activesupport-6.1.5.1/lib/active_support/dependencies.rb:299:in `load_dependency'
/Users/bertie/.rvm/gems/ruby-3.0.4/gems/activesupport-6.1.5.1/lib/active_support/dependencies.rb:332:in `require'
/Users/bertie/.rvm/gems/ruby-3.0.4/gems/eventmachine-1.2.7/lib/eventmachine.rb:8:in `<main>'
/Users/bertie/.rvm/gems/ruby-3.0.4/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/Users/bertie/.rvm/gems/ruby-3.0.4/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/Users/bertie/.rvm/gems/ruby-3.0.4/gems/activesupport-6.1.5.1/lib/active_support/dependencies.rb:332:in `block in require'
/Users/bertie/.rvm/gems/ruby-3.0.4/gems/activesupport-6.1.5.1/lib/active_support/dependencies.rb:299:in `load_dependency'
/Users/bertie/.rvm/gems/ruby-3.0.4/gems/activesupport-6.1.5.1/lib/active_support/dependencies.rb:332:in `require'
/Users/bertie/.rvm/gems/ruby-3.0.4/gems/em-http-request-1.1.7/lib/em-http.rb:1:in `<main>'
/Users/bertie/.rvm/gems/ruby-3.0.4/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/Users/bertie/.rvm/gems/ruby-3.0.4/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/Users/bertie/.rvm/gems/ruby-3.0.4/gems/activesupport-6.1.5.1/lib/active_support/dependencies.rb:332:in `block in require'
/Users/bertie/.rvm/gems/ruby-3.0.4/gems/activesupport-6.1.5.1/lib/active_support/dependencies.rb:299:in `load_dependency'
/Users/bertie/.rvm/gems/ruby-3.0.4/gems/activesupport-6.1.5.1/lib/active_support/dependencies.rb:332:in `require'
/Users/bertie/.rvm/gems/ruby-3.0.4/gems/em-http-request-1.1.7/lib/em-http-request.rb:1:in `<main>'
/Users/bertie/.rvm/gems/ruby-3.0.4/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/Users/bertie/.rvm/gems/ruby-3.0.4/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/Users/bertie/.rvm/gems/ruby-3.0.4/gems/activesupport-6.1.5.1/lib/active_support/dependencies.rb:332:in `block in require'
/Users/bertie/.rvm/gems/ruby-3.0.4/gems/activesupport-6.1.5.1/lib/active_support/dependencies.rb:299:in `load_dependency'
/Users/bertie/.rvm/gems/ruby-3.0.4/gems/activesupport-6.1.5.1/lib/active_support/dependencies.rb:332:in `require'
/Users/bertie/.rvm/gems/ruby-3.0.4/bundler/gems/coinbase-exchange-61cf87cd3d12/lib/coinbase/exchange.rb:5:in `<main>'
/Users/bertie/.rvm/gems/ruby-3.0.4/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/Users/bertie/.rvm/gems/ruby-3.0.4/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/Users/bertie/Projects/meetcleo/config/application.rb:24:in `<top (required)>'
/Users/bertie/Projects/meetcleo/Rakefile:4:in `require'
/Users/bertie/Projects/meetcleo/Rakefile:4:in `<top (required)>'
/Users/bertie/.rvm/gems/ruby-3.0.4/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/Users/bertie/.rvm/gems/ruby-3.0.4/bin/ruby_executable_hooks:22:in `eval'
/Users/bertie/.rvm/gems/ruby-3.0.4/bin/ruby_executable_hooks:22:in `<main>'

Caused by:
LoadError: cannot load such file -- coinbase-exchange
/Users/bertie/.rvm/gems/ruby-3.0.4/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:15:in `require'
/Users/bertie/.rvm/gems/ruby-3.0.4/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:15:in `require'
/Users/bertie/Projects/meetcleo/config/application.rb:24:in `<top (required)>'
/Users/bertie/Projects/meetcleo/Rakefile:4:in `require'
/Users/bertie/Projects/meetcleo/Rakefile:4:in `<top (required)>'
/Users/bertie/.rvm/gems/ruby-3.0.4/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/Users/bertie/.rvm/gems/ruby-3.0.4/bin/ruby_executable_hooks:22:in `eval'
/Users/bertie/.rvm/gems/ruby-3.0.4/bin/ruby_executable_hooks:22:in `<main>'
(See full trace by running task with --trace)
```

**Comment by BertZZ** [comment]
Solved by https://github.com/eventmachine/eventmachine/issues/960#issuecomment-1059459915
